### ISSUE TITLE
Set up Launchpad mirror

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3470]
Set up a Launchpad mirror so that we can get the daily PPA moving again. Ideas:

* Bunnybot
* https://help.launchpad.net/Code/Imports
* https://help.launchpad.net/Code/Git

**Comment by Noordfrees** [comment]
Should actually not be that hard. IMHO the best solution would be a GitHub action that runs on every push to master:
- `git clone --depth 1 https://github.com/widelands/widelands.git master`
- `bzr branch lp:widelands trunk`
- login to bzr as bunnybot
- clear the `trunk` directory (except `.bzr`) and copy all files (except `.git`) from `master` to `trunk`
- rename all `.git*` → `.bzr*` (except `.github`)
- commit and push

If an admin adds bunnybot's private SSH key as a GitHub secret, I can write such an action…

**Comment by Noordfrees** [comment]
I have a functional branch for a LP mirror:
https://github.com/Noordfrees/widelands/tree/lp-mirror
https://code.launchpad.net/~widelands-dev/widelands/test-github-mirror
All that is needed now to complete the mirror is to give the action access to Bunnybot's LP account… (@SirVer ?)

**Comment by gunchleoc** [comment]
Is there a way to give the pushes to the mirror commit messages?

We could also pick a somewhat higher depth to get more than 1 commit, there have been a few since the move...

I had been contemplating the https://help.launchpad.net/Code/Imports way, but controlling it ourselves from here sounds more attractive :)

**Comment by Noordfrees** [comment]
The empty message was only an oversight. If I didn't introduce another typo, the next push (in 10min, because that's the action's running time) will have a message in the format "`gunchleoc: Create spritesheets for trees (#3702)`"

Pushing one git commit at a time would be doable but very tricky, especially as it could be hard to find out which git commit a certain bzr revision refers to. Once the mirror is working it will most of the time be pushed one at a time anyway since we rarely have two commits to master within 15 minutes. 
Do we really need to keep the complete bzr history tidy, or would it be OK to just squash all commits since september into one big push this once (and when there are two commits to master within a few minutes, to also squash these two into one)?

**Comment by gunchleoc** [comment]
I think squashing would be fine, since the sole purpose of the mirror is to provide us with a PPA. I'd like to hear the opinion of @SirVer on this though, since he has more experience with project management than I do.

**Comment by SirVer** [comment]
Sorry for the late reply, I am rather busy reorganizing my professional life currently.

A few thoughts:
- where are maintainers getting their package from? If some choose to use Launchpad, having not a 1:1 mapping between bzr and git commits will make bug reports and also maintainers life hard. 
- If the mirror is truly only for our own PPA it seems inconsequential if commits are squashed or not - as long as we have means of tracing bug reports back to the master SHA that people actually ran on their system. If this is a very manual process, we will likely not do it correctly and hence bug reports become less useful to us.
- the proposed solution by @Noordfrees using the GitHub action seems fragile to me - it will not track renames correctly and it might stumble over incompatibilities between git & bzr (one thing that comes to mind is binary file detection). It sounds quite similar to what bunnybot did, which we all know was fairly fragile. To me, outsourcing the problem to Launchpad seems preferable, i.e. using their import facilities: https://help.launchpad.net/Code/Imports.

Of course these are just my opinions on a quick glance and a few minutes of thinking about these issues, I might be wrong on any or all points.

**Comment by Noordfrees** [comment]
regarding 2): The action includes the github SHA in the LP commit message so this can be translated at one glance
re 3): "Fortunately" our current changes have such incompatibilities already, which caused bzr to crash frequently in my first tests. I am fixing this by running `bzr remove; bzr add` which fixes all these problems, only renaming will not be detected this way. But since we use LP only for packaging is there really a reason why we need to keep the LP history clean in this regard?

**Comment by SirVer** [comment]
2) that sounds sufficient then, IMHO.
3) I cannot answer that question besides the points I mentioned above. I still think letting Launchpad deal with the headaches of importing is saving resources for the Widelands project, but since you @Noordfrees seem to be eager to own and maintain this piece of infrastructure, that might not be an issue either.

**Comment by gunchleoc** [comment]
I am leaning towards https://help.launchpad.net/Code/Git#Mirroring_repositories_from_other_sites now. This will probably mess with our legacy branch history on Launchpad, but it would avoid the git->bzr conversion. I don't think we need that history any more at this point.

**Comment by Noordfrees** [comment]
In my opinion, taking care of the mirroring ourselves is preferable to relying on LP to do it for us. The action approach is similar to old bunnybot except that it's far more stable because the logs and any possible failures are publicly visible and can be taken care of by every developer with no more effort than a PR. I would happily be responsible for maintaining the mirror action.

**Comment by gunchleoc** [comment]
OK, let's to the GitHub actions route then, and thanks for offering to maintain it :)

Because it gives us control, we can always change strategy later if it should cause us problems.

**Comment by SirVer** [comment]
let's do it! Thanks, @Noordfrees

**Comment by Noordfrees** [comment]
Okay! @SirVer Could you then please send me bunnybot's LP login credentials (password or private SSH key)? As soon as I have those the mirror is ready for use :)

**Comment by SirVer** [comment]
@Noordfrees I moved the credentials conversation to email.
