### ISSUE TITLE
Avoid double CI builds

### ISSUE THREAD

**Issue by TinoM** [widelands/widelands#3494]
Example: https://github.com/widelands/widelands/pull/3488

Both Appveyor and Travis do run a build for both all branches and merge requests.
If we have a merge request to master from a branch in the widelands repo itself, overall 4 jobs are triggered.

**Comment by stonerl** [comment]
Should be solved now. I configured the webhooks to only fire for PRs.

**Comment by gunchleoc** [comment]
Of course, we now lose the capability of getting builds without making a pull request first.

Should we keep the branches at least for AppVeyor, for example so that people can test the Amazons without us having a premature pull request?

**Comment by stonerl** [comment]
We could try to get the Windows test on Travis running. Then we use Travis for PR and Appveyor for pushes.

**Comment by gunchleoc** [comment]
I have now edited the .yml files to be restricted on the master branch and pushed the chnage directly. If people are working on a branch, they can add their branch to the list in the yml files. I'll create some test branches to verify that we will get a build on every push.

Excluding branch & tag creation is OK, because we should get builds with a push anyway.

Once I have verified that it works, we can add documentation to the wiki.

**Comment by stonerl** [comment]
I'm currently reworking travis.yml as well, without the restrictions to build just one branch. It will take some time, though. Cod you wait with the edit in the wiki, please?

**Comment by gunchleoc** [comment]
I will definitely wait until everything has been worked out.

Here's the test branch: https://github.com/widelands/widelands/tree/this-branch-should-be-built-by-travis

ETA: Tested and working, so I'll delete the test branch again.

**Comment by gunchleoc** [comment]
I have documented the `branches` thing in https://github.com/widelands/widelands/blob/master/README.md#obtaining-travis-and-appveyor-builds
