### ISSUE TITLE
Accessing multiplayer lobby as unregistered user crashes the game

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#3501]
The error says:

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Abgebrochen (Speicherabzug geschrieben)
```

Did not tried as a registered user.

See also: https://www.widelands.org/forum/post/29883/

**Comment by stonerl** [comment]
Have to investigate this. This didn't happen when we introduced the change in April/May.

**Comment by frankystone** [comment]
This is maybe tricky, because '_M_construct' can only be found in the build directory after compiling.

**Comment by Notabilis** [comment]
The metaserver logs do not show anything about these login attempts.
Relavant excerpt from the gdb backtrace:

`#7  0x00005555571b8196 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*> (this=0x7fffffff4940, __beg=0x0, 
    __end=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>) at /usr/include/c++/8/bits/basic_string.tcc:212`

`#8  0x0000555556af4933 in FullscreenMenuMultiPlayer::internet_login (this=0x7fffffff6bb0) at ../src/ui_fsmenu/multiplayer.cc:114`

**Comment by Notabilis** [comment]
The referenced line is:
`std::string auth = register_ ? password_ : get_config_string("uuid", nullptr);`
I guess the `nullptr` is the bug here and should be `""` or something like that. Inside the `get_config_string()` method the `nullptr` is dereferenced (file wlapplication_options.cc).

Can someone please create a branch for this (and similar places)? I haven't set up Git yet.
