### ISSUE TITLE
After upgriding mine to deeper mine food is not delivered

### ISSUE THREAD

**Issue by Kicer86** [widelands/widelands#3505]
As soon as I have updated mine to deeper one food stopped to be delivered.
It happened to all upgraded mines

**Comment by gunchleoc** [comment]
Do you have a savegame that you can attach ad a zip file?

**Comment by Kicer86** [comment]
[otwarty swiat.zip](https://github.com/widelands/widelands/files/3632453/otwarty.swiat.zip)
Here is the original save file with changed extension to zip.
Take a look at the deeper marble mines on north. There are three of them, two are disabled and one is enabled. All suffer from this issue. I also had other mines with this problem but I destroyed them.

Another similar issue was on the south where coal mines are. There are two but there was third between them being built. It never finished. There was only one plank needed. And it never got there. There were a few buildings around started later and all of them were successfully built. I have even increased the priority from yellow light to green one, but it didn't help.

**Comment by frankystone** [comment]
The upgraded mines do not work because meal is missing. Meal is produced in the Inn, which can be enhanced from a Tavern. You haven't an Inn so far... at least in this savegame.

As soon you decide to upgrade an empire mine you must upgrade a Tavern to an Inn too. A tavern produces only snacks, an Inn produces snacks and meal.

The thing with 'buildings does not finished' is a known bug and will be fixed in the next official release.

I think this bug is invalid. Feel free to reopen it again.
