### ISSUE TITLE
Can't load Build 20 save: unknown ware type "thatch_reed"

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#3529]
- Affected savegame: [215.wgf](https://www.widelands.org/forum/attachment/570041fdadfb373fde9ee7402e3230d679be8330/)

Trying to load this savegame (saved in Build 20) results in the following error:
```
Game data error
buildings: unknown ware type "thatch_reed"
```
Likely related to the following commits:

777771e9ed Renamed thatch reed to reed.
c7e8e09267 Fix savegame compatibility for reed, buildings, players view and economy requests.

 - OS: Manjaro Linux
 - Widelands Version: Current master (9f6391ed7e)

**Comment by jmoerschbach** [comment]
I can confirm with just another savegame and different error message (exception)

`../src/map_io/map_object_packed.cc:120: load_pointers for ship: not found`
[bla.zip](https://github.com/widelands/widelands/files/3665501/bla.zip)



OS: Windows 10
Widelands Version: git-b'6b496 (master) (Release)

**Comment by jmoerschbach** [comment]
Hi,
I just looked into "my" problematic savegame which cannot be loaded by current master (problem with ships).

I narrowed it down to following line:
https://github.com/widelands/widelands/blob/9e297d10a68b50be723b6e0f930b7673c3120aab/src/logic/map_objects/tribes/ship.cc#L1408

When I comment this one out, savegame can be loaded. 
The call to mol().get<PortDock>(pair.first) results in a exception being thrown because there is no PortDock (which is correct, I didn't build one).

So I think the error is before: Why is the for-loop executed in the first place? I don't have enough contextual knowledge yet (does every ship always need to have at least one destination?).
However, there are only to spots where destinations are pushed in, and it looks somewhat suspicious to me :)

https://github.com/widelands/widelands/blob/9e297d10a68b50be723b6e0f930b7673c3120aab/src/logic/map_objects/tribes/ship.cc#L1381-L1391

It might be related to 6b496248e243e6231eab7de1c07276ca6c20a3a5

I think the original issue (thath_reed) and the ship problem are two different issues, so maybe separate them?
I'll be on vacation for the next 2 weeks, so don't expect any news from me until then ;)

**Comment by Noordfrees** [comment]
The ship-loading issue is a corner case in savegame compatibility code, will be an easy fix

**Comment by jmoerschbach** [comment]
So one last comment because I couldn't help thinking about it :D

Incompatibility has indeed be introduced by 6b49624 (verified by switching to 9f6391ed7eef64cdf1321c6308160a07d19c89d3 which works fine)

Problem is that fr.unsigned_32() returns 0 which seems to be non-valid value. It has been checked/ignored in old code 

https://github.com/widelands/widelands/blob/e314409fd21023ca16ef716fedcde8b1f3c9dd76/src/logic/map_objects/tribes/ship.cc#L1212-L1213

but now it is treated as a valid destination and pushed into the list of destinations
