### ISSUE TITLE
Flatpack for the development (master) branch

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands#3558]
I wonder if we could provide a flatpack for the development branch that updates ervery time we push something to master. This would help to address more user. @scx  could you help us out here?

**Comment by scx** [comment]
I will try. However, as far as I know, Flathub requires "stable releases, reproducible builds".
https://github.com/flathub/flathub/wiki/App-Requirements#stable-releases-reproducible-builds
Not sure how this applies to the `beta` channel, but I am afraid that we will have to type specific commit anyway.

**Comment by scx** [comment]
@stonerl 
What is the most suitable version string (`WL_VERSION`) for such a "release"?
- `r24271[e8dd143@HEAD]` (default)
- `r24271`
- `Build 20+r24271`
- `Build 21~r24271`

What do you think about it?

**Comment by stonerl** [comment]
The default one.

**Comment by scx** [comment]
And what about the AppData file?
Is it rather `Build 20` with some enhancements or development version of `Build 21`?

**Comment by stonerl** [comment]
`Build 21` since master will eventually branch into the next release, that will be build 21

**Comment by scx** [comment]
@stonerl 
Done: https://github.com/flathub/org.widelands.Widelands/pull/9

Sorry for a small delay, but I have to test it, and there was an issue with calculating the revision number, because of shallow clone, which is used by default by `flatpak-builder`.

Now it works correctly.
```
$ xmlstarlet sel -t -v '/component/releases/release[1]/@version' -n build/files/share/appdata/org.widelands.Widelands.appdata.xml 
Build 21~r24272
```

As for version string, it still use the default value.
```
$ echo "$( cat build/files/share/widelands/VERSION )"
r24272[87b0494@HEAD]
```

Anyway, the `beta` channel should available within 24 hours.
More info:
https://github.com/flathub/flathub/wiki/App-Maintenance#the-repository
https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/

I've also provided the standalone package:
https://github.com/scx/widelands-flatpak/releases
https://github.com/scx/widelands-flatpak/releases/tag/v21-r24272+20191115

The main difference is that it uses `Build 21~r24272` as the version string as well.
https://github.com/scx/widelands-flatpak/blob/v21-r24272+20191115/Widelands.yaml#L46
```
$ echo "$( cat build/files/share/widelands/VERSION )"
Build 21~r24272
```

Moreover, Flathub version uses the `beta` branch.
https://github.com/flathub/org.widelands.Widelands/pull/10

If you want to update it, just change the `commit` value.
https://github.com/flathub/org.widelands.Widelands/blob/03c9599f6a3ca9b7cfd7692888755afdbe7ed89c/org.widelands.Widelands.yaml#L89

**Comment by stonerl** [comment]
Thanks alot. How do we publish new builds? Just change the sha1 of the commit value and open a PR?

**Comment by scx** [comment]
@stonerl 
> Thanks alot. How do we publish new builds? Just change the sha1 of the commit value and open a PR?

Yes, all you need to do is change the commit value and make a PR.
https://github.com/flathub/org.widelands.Widelands/blob/beta/org.widelands.Widelands.yaml#L89

Just remember, you have to use the `beta` branch.
https://github.com/flathub/org.widelands.Widelands/tree/beta

**Comment by stonerl** [comment]
@scx Where do I find the beta on the flathub site?

https://flathub.org/apps/details/org.widelands.Widelands

Is only the release build.

**Comment by scx** [comment]
@stonerl 
> Where do I find the beta on the flathub site?
> 
> https://flathub.org/apps/details/org.widelands.Widelands
> 
> Is only the release build.

Unfortunately, unlike Snapcraft, Flathub doesn't show channels other than stable (`master`) on its site.

Oct 13, 2019:
```
18:01 < Calinou> is there a web frontend for packages on the flathub-beta branch?
18:01 < Calinou> I'd like to link to a beta page for https://flathub.org/apps/details/org.godotengine.Godot in a tweet :)
18:52 < barthalion> sadly, no
```

However, as far as I know, it should be visible in [GNOME Software](https://wiki.gnome.org/Apps/Software).

Anyway, if you're looking for installation instructions, you'll find it here:
https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/

**Comment by stonerl** [comment]
> Unfortunately, unlike Snapcraft, Flathub doesn't show channels other than stable (`master`) on its site.

Thanks that's what I wanted to know.
