### ISSUE TITLE
Seafaring tutorial improvements

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3675]
I'd like to see the following tweaks in the seafaring tutorial:

Seafaring part:

1. Start the Ship Yard objective while the port is still building, because both the port and the ships take a long time to build. This will speed things up for the player.

Ferries part:

1. We could break up the wall of explanation text a bit by asking the player to build a ferry yard first, then explain more about waterways while it's being built, and then also demonstrate the waterway building in between the explanations.
2. Scroll to where the player is supposed to build the goldmine. I have no clue where the scenario wants it built.

**Comment by pospec4444** [comment]
I've started working on seafaring part: 2573cc923a0d440d5879e402e1f0ad4dceef8a09
Unfortunately, I couldn't find out how to know if player builds Port or something else...

**Comment by Noordfrees** [comment]
>  Unfortunately, I couldn't find out how to know if player builds Port or something else...

Since the port can be built only at one spot, you can check for `this_one_field.immovable and this_one_field.immovable.descr.type_name == "constructionsite" and this_one_field.immovable.building == "atlanteans_port"` ([constructionsites](https://www.widelands.org/documentation/autogen_wl_map/#constructionsite) have a property "building" that allows you to check this)

**Comment by pospec4444** [comment]
Thanks, I've missed this one.

**Comment by pospec4444** [comment]
As #3782 and #3788 are merged, can this issue be closed?

**Comment by Noordfrees** [comment]
Yes :)
