### ISSUE TITLE
Let player pick a starting position

### ISSUE THREAD

**Issue by fenjen** [widelands/widelands#3685]
In the past days, I've very much enjoyed playing Widelands with some friends. Most of us used to play _The Settlers 1_ when we were young. We however all agreed that picking a decent starting position was an important strategic factor. It also gives the player a deeper understanding of the map, and helps the player identifying with the settlement. I think it would be great having an option for that on the launch screen.

Here's what I would expect when this option is selected:

1. Game starts, the world is entirely visible.
2. A window with a button pops up. When clicked, a new settlement is created in the center of the screen.
3. The player(s) can search around and find a position of choice.
4. When the new settlement is created, the player can start playing immediately. Being too picky on the start position has two disadvantages:
    1. Other human players may pick a position one was hesitating on.
    2. Opponents get to start earlier.

I think it's good to requite players who pick their starting position fast.

**Implementation steps**
The changes would have to be done in both single- and multiplayer custom games.

***Launch custom game screen***
- New checkbox "Let players pick their starting position".
- When checked, the starting settlement type is grayed out and shows "Headquaters".
- Caption of the team selection button shows  "Switch team color" instead of "Switch to position".

***Game start***
If that new option was selected:
- AI players pick immediately one of the map defined starting points (by random)
- For the current non-AI player
  - the entire world is visible (incl. other players settlements)
  - a window appears with an action button for creating headquaters (window is non-closable)
  - the player can search around and click that button
  - when the button is clicked
     - there needs to be a check whether that starting position is valid (there's space for the building and there's a minimum margin to other players)
     - If the place is invalid: display message with the reason
     - If the place is valid: put headquaters at that position

Improvements:
- Quick animation when headquaters is being built
- Show vague data about nearby resources

**Comment by fenjen** [comment]
![startpos](https://user-images.githubusercontent.com/2162388/74105695-7334b880-4b60-11ea-9835-5732d9d759dd.png)
Simple mockup

**Comment by Noordfrees** [comment]
I like the idea very much :)

IMHO we could allow all starting conditions here, and the player gets to decide which field the HQ/village is centered on. This should be as easy as setting the map's n-th starting position to the spot the n-th player clicks on.

This would have to go into the InteractiveGameBase – a new variable `starting_position_selection_mode_`, and while it's `true`, a leftclick on the map results in the player's starting position to be set to this node if it meets the criteria and then invoking the chosen starting condition script.

Downside: The whole map needs to be visible during this process, which gives players who hesitate longer a clear advantage. IMHO the whole map should be reset to "previously seen" state after picking a spot, and when another player claims a spot its region should immediately be marked as "previously seen" for all other players to prevent spying.

Displaying resource info is not something I'd like, because it just gives players advantages they normally don't have. But we should show indicators for the default starting positions to give players a clue from where they will likely have a good chance.

**Comment by tibor95** [comment]
I think there is minimal distance between headquarters defined, so the selection would not be completely free, moreover prohibited areas (headquarters + radius) might just be invisible (dark)

**Comment by fenjen** [comment]
@Noordfrees: I am very happy about the quick responses. Concerning the resources... I found it a bit necessary, because otherwise people could get stuck i. e. when they're not able to gather certain resources for manufactoring tools. I thought, that if all people have access to that information, no one would have an advantage. But in any case it would be crucial to obscur this information in order to prevent people from concluding exact positions of resources by scrolling back and forth.
