### ISSUE TITLE
Add a Lua scripting function to place waterways

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3687]
Jut like `LuaPlayerBase::place_flag`, it would be good to have a function to place waterways via the Lua interface for scenario scripting.

We could then also add a function `connected_waterway` to `scripting(infrastructure.lua`.

**Comment by Noordfrees** [comment]
There is no significant distinction between roads and waterways in Lua, the class `LuaRoad` functions as a lua equivalent for `RoadBase`. And I´m planning to also cleanup the IBase to unify road- & ww-buildingmodes into one mode with a bool param so the two concepts share as much code as possible. 

So IMHO instead of duplicating these functions, we should allow passing an optional parameter `type` (default *normal*) to `LuaPlayer::place_road` and the lua convenience functions using it, which defines whether the RoadBase created becomes a *normal* (road), *busy* (road) or *waterway*.

**Comment by Noordfrees** [comment]
Will have to implement this anyway to address your review comments in #3662 ;)

**Comment by gunchleoc** [comment]
+1 for the optional parameter :)

The only scenario in master that uses it directly at this point is Empire4, everybody else is using the helper function in `data/scripting/infrastructure.lua`. So, we might even make it required.
