### ISSUE TITLE
Merge "transform" and "grow" immovable programs

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3691]
The "transform" and "grow" immovable programs both do the same, except for some differences in parameters.

1. [ ] Replace "grow" with "transform", making sure that tha parameters work
2. [ ] Add saveloading compatibility code for games

**Comment by hessenfarmer** [comment]
I believe the difference is that transform is not taking terrain affinity into account while grow does. So this is a big difference in result.

**Comment by gunchleoc** [comment]
I did indeed miss that. I'm wondering whether we could make this difference a parameter. I'd be fine with not changing anything though.

**Comment by hessenfarmer** [comment]
I would vote for keeping things as they are. Mainly for keepin the telling program names which make reading the immovable programs easier.

**Comment by Noordfrees** [comment]
Currently trees have programs like `"remove=21","grow=…"`. IMHO it would be better if this was unified into one program that accepts an optional param for a remove chance and autodetects whether the immovable has terrain affinity. The remove chance should then be weighted with the terrain goodness, and instead of increasing the growth time for bad terrains remove the immovable with a chance that is the higher the worse the terrain matches the preference.

**Comment by gunchleoc** [comment]
The tribe immovables also use `remove` (ashes, harvested fields). Shipconstruction uses `transform` without a separate `remove`. So, if we want to combine `grow` with `remove`, how about combining `transform` and `remove` too? If `transform` is called without an object, simply remove the object.

**Comment by gunchleoc** [comment]
The merging of the programs has been rejected to give Lua coders more control.
