### ISSUE TITLE
Window snapping to right edge makes buttons unreachable

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands#3811]
To save some screen space, window snapping & positioning to the screen edge is omitting the window's border. This will hide the new window pin and close buttons now.

**To Reproduce**
Situation 1:
1. Play Tutorial 1 until you reach the "Building Spaces" message.

Situation 2:
1. Go to Options -> WIndows and ensure that "Dock windows to edges" is switched on"
2. Start a game or the editor and move a window with the mouse to the right or left screen edge.

![close_button](https://user-images.githubusercontent.com/4095570/77815530-c7b1da00-70b3-11ea-830c-4863d8a576ff.png)

**Comment by stonerl** [comment]
Could we make them smaller,  please? 10px and have a spacing of 2px between them, so they look like normal window buttons? And on the right-hand site. I made a mock-up:

![shot0001](https://user-images.githubusercontent.com/2091312/77855194-32b3fb80-71ef-11ea-8bab-303e3d8a3d84.png)

**Comment by Noordfrees** [comment]
10 px makes for a tiny click target imho. I'll make them a bit smaller though and add the spacing. 
I originally positioned them all on the left but the close button was moved to the other side in code review to prevent annoying misclicks.
Edit: Moving the buttons away from the left/right edge as in the mockup should be avoided as we are running out of space for the window title for many windows

**Comment by gunchleoc** [comment]
> Moving the buttons away from the left/right edge as in the mockup should be avoided as we are running out of space for the window title for many windows

Good point. People are also used to the close button being in the corner from every other software under the sun, so we shouldn't break that convention.

I'd be OK with having them all on the right-hand side though, because then the pin button is separated fro the close button via the minimize button.

**Comment by Noordfrees** [comment]
Personally I rather like the window layout of OpenTTD – close button in the left corner, pin/restore_size/minimize buttons in the right corner. This feels more familiar to me than what most window managers use (except that it's mirrored from what I consider intuitive :D )

**Comment by frankystone** [comment]
My opinion: If one moves a window to the right he want's to have this window open, or may minimize it. So if the close button is out of  the screen it doesn't matter much. Closing can also be done via right click.

Don't know why i move windows always to the right (maybe because i am right handed?). If one used to have opened windows to the left screen, this may can be an issue...

In any case there are the old ways to close/minimize a window. I would say lets leave it like it is.

**Comment by gunchleoc** [comment]
Do you use window docking to edges?

I like the window layout as it is in master, I'd only change the docking and/or the placement of campaign story boxes. I noticed this when playing the tutorial and not while manually placing windows myself somewhere.

**Comment by frankystone** [comment]
> Do you use window docking to edges?

Yes, all the time.

> I like the window layout as it is in master, I'd only change the docking and/or the placement of campaign story boxes. I noticed this when playing the tutorial and not while manually placing windows myself somewhere.

+1

**Comment by frankystone** [comment]
Docking to edges is disabled by default. So new players may do not notice this problem in tutorials or scenarios. Enabling this feature is mostly done by more experienced players, imho, and they know how to handle windows without having a window border visible.

In general i wouldn't change this as long nobody complains. If feasible in an easy manner, placing of scenario story boxes can be adjusted so that they do not dock. AFAIK this applies only to [campaign_message_box](https://www.widelands.org/documentation/autogen_auxiliary_messages/#campaign_message_box)

**Comment by Noordfrees** [comment]
Marking as urgent because a PR for this is open
