### ISSUE TITLE
REPLAY: Lost synchronization

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#3819]
**Describe the bug**
When playing back a replay the game stops and prints a message like this in the terminal:
```
REPLAY: Lost synchronization at time 3400
I have:     3f238ef082a3e54480065f81794388fb
Replay has: e56c3f70389ac2512c8219f6608aea23
```

**To Reproduce**
1. Start a new game on [Tasmanian Black War](https://www.widelands.org/maps/tasmanian-black-war/). Use default settings.
2. Wait 10 seconds then exit the game.
3. Load the replay of the game you just played and wait a few seconds.

**Version:**
 - OS: Manjaro Linux
 - Widelands Version: All versions starting with 7e2902c69a67bed3c3d545eb5e358afb18bae104 (first bad commit), including ff9bae926281db480a85c3840bffc4f2e4850f58 (current master)

**Comment by Noordfrees** [comment]
Tried that with 453c2ebd8066e7a1577a9b395e51907e4587db55 (same map, default settings) and everything worked fine. Do you have specific instructions to make a desync more likely?

**Comment by Noordfrees** [comment]
Also did you test with release builds, debug builds, or both?

**Comment by simply-peachy** [comment]
Just tried with r24527[453c2eb@master] (Release), started a single player game on Crater with all default settings, built a lumberjack, let the game run for a few minutes. Exited, played replay and it desynced after a short while. I'll try a debug build now.

**Comment by frankystone** [comment]
I can confirm this with a debug build on [453c2eb@master].

Crater, initial settings, build some lumberjacks, a gamekeeper and a hunter. After 2 Minutes i have saved the game.

The replay of this game looses **sometimes** synchronization. With 'sometimes' i mean: Sometimes the replay ran through, sometimes it looses synchronization. So one has to start watching the replay more often.

**Comment by Noordfrees** [comment]
I started five more such games now and watched each replay eight times and got exactly zero desyncs :(

**Comment by frankystone** [comment]
Just my observations, don't know if they are related:

On a fresh start of widelands and watching the replay it ran through. Close game (not widelands) -> watch replay the second time -> desync. After this watching the replay doesn't desync anymore (started it about 6 times without getting a desync)

Seems to me that if a desync doesn't happen in the few seconds, all is fine.

Some how i have managed to get two desync messages:
~~~~
Message: adding warehouse for player 2 at (51, 27)
REPLAY: Lost synchronization at time 25200
I have:     d4549f618ccd69c484622a10c4abd65d
Replay has: e6ac35fc59d677bb1b892ad4813c8818
REPLAY: Lost synchronization at time 25400
I have:     a640ffa3685d4295c43747c9110b886f
Replay has: 16f06eb9c2ebd21e0c95bdcb701c8064
~~~~

**Comment by Noordfrees** [comment]
Could you upload this replay and the savegame?

**Comment by frankystone** [comment]
Here they are. The savegame isn't compressed.

[desyncs.zip](https://github.com/widelands/widelands/files/4416886/desyncs.zip)

**Comment by Noordfrees** [comment]
Yay, this desyncs for me :)
```
REPLAY: Lost synchronization at time 15800
I have:     e7dbc4564166bf24f0a9fbaa8ca615ea
Replay has: 8e9d125f9a6bcb17bec7b3d890b45d5f
```
Now I can try to see whether I can find a clue to a clue to identifying which code part the problem might be lying in ;)

**Comment by frankystone** [comment]
Thanks for all your work :-)

**Comment by Noordfrees** [comment]
Thank me when I found the reason ;) 
So far I found out that the last sync report just before the desync refers to a Worker's act() function being called. That's all the syncstreaming will tell me. Now I'll have to try to catch all act()s in a debugger and filter out the one important one…

**Comment by Noordfrees** [comment]
(just using this issue as a lab book…)

The Map Object in question, serial 750, is a barbarian builder belonging to player 2, at 53×26; stack with 1 task, namely `{{task = 0x5555583acbc0 <Widelands::Worker::taskBuildingwork>, ivar1 = 1, ivar2 = 0, ivar3 = 0, objvar1 = {serial_ = 0}, svar1 = "", coords = {x = -1, y = -1}, 
    diranims = {animations_ = {0, 0, 0, 0, 0, 0}}, path = 0x0, route = 0x0, program = 0x0}}`

Argh, the syncstream left out some important information, so I can't be sure our poor builder is really the problem…

**Comment by Noordfrees** [comment]
No, it is of course not as easy as it seems. To debug this properly I need the syncstream for the original savegame as well.
@frankystone or @simply-peachy  could one of you please try the following:
- go to `src/logic/game.cc` and uncomment line 73 (remove the three slashes before the ` #define SYNC_DEBUG`) and recompile (preferably as debug build)
- start the game from the commandline and redirect output to a logfile (`./widelands > desync.log`)
- play one (!) game to create a problematic replay (NOTE: the logfile will have ~ 1 MB size per 10 seconds played)
- close widelands, and start it again without redirecting output
- check that the created replay desyncs
- upload replay and logfile

Since I still have no luck at creating a desyncing replay myself I hope that you have more success here (and that my instructions are understandable and doable)…

**Comment by Niektory** [comment]
@Noordfrees I was unable to reproduce with a debug build so I used a release build. Hopefully the results are still useful.

Version: 453c2ebd8066e7a1577a9b395e51907e4587db55 (release) with `#define SYNC_DEBUG` uncommented
Log and replay: [desync.zip](https://github.com/widelands/widelands/files/4418484/desync.zip)

For me the replay doesn't always desync if I play it for the first time after launching Widelands, but if I load it a second time (without closing Widelands) then it desyncs.

**Comment by frankystone** [comment]
Here the files with a debug build. On a first test this replay desyncs at 1:09 when trying to watch it the second time:

~~~~
[sync:00295373 t= 69597] 84    
[sync:00295374 t= 69597] ec 08 a8 ce
REPLAY: Lost synchronization at time 69600
I have:     d9058fb9bdef607292f38a4d513e4e80   
Replay has: 477514c93790b04601418cd43b7037d6
[sync:00295378 t= 69602] 68
[sync:00295379 t= 69602] e2 0f 01 00 
[sync:00295383 t= 69602] 80 00 00 00
~~~~

I have switched from fullscreen to window mode while watching, just wanted it to mention.

This file contain the replay, a savegame and the desync.log.

[replays.zip](https://github.com/widelands/widelands/files/4419275/replays.zip)

**Comment by Noordfrees** [comment]
*Two* replays with sync reports, wonderful! Now I can really find out where the desyncs come from :)

**Comment by Noordfrees** [comment]
(the lab book continues…)

in kaputtnik's log&replay, we have the following situation: There is an act() command being executed. In the SG, the RNG is called 4 times. Then the next act() command runs and calls the RNG twice. 
In the replay, the first act() calls the RNG **five** times before the next act() calls it again twice. 
My mission now: Find out where the extra RNG call comes from.

The five rands are called from immovable_program.cc, ActSeed::execute, for a birch_summer_mature: first call (af…) in the big if, three calls (89…,cc…,d4…) in the do-while, and one call (53…) in the for loop. It's not being called in the if below because new_location has nodecaps = MOVECAPS_SWIM.

Mit dem Taschenrechner nachgerechnet – das *replay* scheint korrekt zu funktionieren, im *savegame* hingegen fehlt der fünfte RNG-call unerklärlicherweise (vielleicht wird dort das falsche *Programm* ausgeführt?)

In Niektory's replay, we have the same problem: An Immovable (also type 1e/plain Immovable, e.g. trees) is acting (again ActSeed::execute) and calls the RNG **three** times; in the replay we have **five** calls.

It seems as if for some reason the ActSeed simply terminates after the do-while is done. The for loop and the if below seem to be magically skipped in the original game but not in the replay, *why*??

**Comment by Noordfrees** [comment]
Ouch! Found the reason :)
During the program parsers refactoring it seems that the `probability` variable of ActSeed was forgotten to be initialized. An uninitialized variable is the best guarantee for compiler- and platform-specific desyncs. Should be an easy fix…
