### ISSUE TITLE
Resizing map removes all immovables

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#3822]
**To Reproduce**
1. Start editor
2. Place some immovables like trees, stones and ruins
3. Resize the map
4. Click on the map

Result: All immovables get removed

**Expected behavior**
Immovables should stay

**Version:**
 - OS: archlinux
 - Widelands Version: [453c2eb@master] (Debug)

**Additional context**
As mentioned in #3754 the player starting positions [some times do not translate correctly](https://github.com/widelands/widelands/issues/3754#issuecomment-598249982)

**Comment by Noordfrees** [comment]
I have made a branch: https://github.com/Noordfrees/widelands/tree/fix-editor-resize
Shrinking the map in both directions at once is not implemented currently, all other resizing actions are.

@frankystone could you please test whether you can still find undesired behaviour with this branch? 
If not, I'll adapt the changes for the double-shrinking and propose it for merging. If you do find errors, the interesting parts are:
- was the map width de- or increased
- was the map height de- or increased
- if the size was decreased: did you click near the lower/right edge (so that the *preserved* part of the map is "in one piece" looking on the minimap) or near the left/upper edge (so that part of the preserved part is on one side and the other part on the other side on the minimap)
- did it happen when clicking or during undo/redo

**Comment by Noordfrees** [comment]
Never mind implemented it now in a way that hopefully works… 
PR is up
