### ISSUE TITLE
Doubled ware descriptions in Tribal Encyclopedia

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#3882]
Several wares (mead, honey bread, iron, Atlantean smoked fish) in the Tribal Encyclopedia have doubled "wares consumed/produced" sections. This is caused by the duplicate programs added in 726d3d3c1dae4a2dc90cc61d690b5c7066c892dc.

![double_ware_descriptions](https://user-images.githubusercontent.com/4470900/80444063-fd471e80-8910-11ea-8478-d31cad23ed69.png)

 - Widelands Version: 01ae086ebe550d7365176b8cd1c0024009fb74e7

**Comment by pospec4444** [comment]
@hessenfarmer:
> -- 2 identical programs for iron to prevent unnecessary skipping penalty

What is the motivation behind following construct? I don't understand the "skipping penalty" comment.

https://github.com/widelands/widelands/blob/01ae086ebe550d7365176b8cd1c0024009fb74e7/data/tribes/buildings/productionsites/atlanteans/smelting_works/init.lua#L63-L89


@Niektory:
If production site definitions has to stay untouched, does this involve changes in [ware_help_producers_string](https://www.widelands.org/documentation/autogen_lua_tribes_other_ware_help/?highlight=ware_help_producers_string#ware_help_producers_string) ([code](https://github.com/widelands/widelands/blob/058332e34c103af8412f394b60697a7a724e3df3/data/tribes/scripting/help/ware_help.lua#L49))?

**Comment by Niektory** [comment]
> What is the motivation behind following construct? I don't understand the "skipping penalty" comment.

It's explained here: https://www.widelands.org/forum/topic/4523/?page=5#post-30826

The doubled programs were probably a mistake but I don't know what the *proper* fix should be. It's hard to touch anything here without breaking something else...

**Comment by hessenfarmer** [comment]
In fact I didn't think about the ware help when fixing the underlying performance issue. this happens to all productionsites which did call the same program 2 times in a row (only happens if exactly 3 calls) if they have the same name the first is skipped due to the ware not needed and then the next is not attempted for 10seconds. to avoid this I made their names different. But now they appear 2 times in the help.  
fix should be in the ware help I think I already have an idea maybe I'll find some time to provide a branch tonight.  (idea is to check for identical programs (same input and same output)
