### ISSUE TITLE
Stronger Trading Outpost

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#3885]
The Trading Outpost starting condition is used mainly to buff AI players and should therefore be made stronger to allow players to play against a very strong AI. (Since it is a cheating mode anyway it does not need to be balanced among the tribes.)

The starting values for coal, iron, gold, grains, and water, as well as the number of items refilled at a time, should be increased by ~ factor 3. (The construction material values are fine as they are.)

We should also consider making Trading Outpost the default start for AIs in the single-player game setup screen.

**Comment by frankystone** [comment]
> The Trading Outpost starting condition is used mainly to buff AI players and should therefore be made stronger to allow players to play against a very strong AI.

Since the AI is WIP and as far i remember hessenfarmer and Tibor is working already to make it stronger, this should be taken into account.

> We should also consider making Trading Outpost the default start for AIs in the single-player game setup screen.

I am strongly against this. Please keep in mind that most of the people writing here or in the forum are experienced players. For those players such a default may make sense, but for new players such a default might be to difficult. New players already  struggling with the game at all, because it has so many adjusting screws. An experienced player can make this setting easily, while inexperienced players may do not find where this setting is at all.

The game should be playable by new players with default settings, without getting frustrated. If they get familiar with the game, they can adjust the difficulty to fit there needs.

**Comment by Noordfrees** [comment]
This enhancement is an add-on candidate then. If it will be very popular as an add-on we can still consider making it official.

**Comment by Noordfrees** [comment]
Available as an add-on now: https://github.com/widelands/wl_addons_server/tree/master/addons/stronger-trading-outpost.wad
