### ISSUE TITLE
'attempt to call a nil value' when opening help fo farm

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands#3923]
**Describe the bug**
Error message when opening the help for the barbarian's (maybe other tribes as well) help from the buildings window or encyclopedia (see attached screenshot)

**To Reproduce**
1. Place a farm.
2. Open the buildings window.
3. Click on the help button.
4 See the error.

After a while this error disappears (after opening the encyclopedia a couple of times).

**Screenshots**
<img width="912" alt="image" src="https://user-images.githubusercontent.com/2091312/82739780-df6bae80-9d42-11ea-953d-1fa5489e523e.png">

**Version:**
 - macOS 10.15.4
 - master (f929084c51)

**Comment by Noordfrees** [comment]
Cannot reproduce, the helptext is shown normally to me…

EDIT: After writing this and then trying again I suddenly *can* reproduce…

EDIT2 apparently just a missing lua include in some help-related script

**Comment by hessenfarmer** [comment]
I can't reproduce this in my windows builds. Could you provide a log (stdout.txt) for this issue. 
I can't see why the aditional include should help here

**Comment by Noordfrees** [comment]
- start a new game as barbarians
- place a farm csite
- open the building window
- click the help button in the building window

Then you should be able to see the error. 
The moment you open the encyclopedia and select some entry that does not show this behaviour (which may also apply to the default entry!) the missing include is included and the problem fixed. The solution is to include the script defining the performance time functions directly from building_help.lua rather than relying on its being included from somewhere else.

**Comment by hessenfarmer** [comment]
Ok understood now. the script is currently called in some of the helptexts.lua where not all texts have been defined. So the issue is a bit more complex. First of all the global helptexts are the wrong place to define the time formatting functions. they should be moved to the format_help.lua which is already included in building_help.lua this would fix the issue properly I believe. By this we would leave the global_helptexts.lua with its original purpose to define standard helptexts. See the line above every instance where it is still included. (e.g. babrbarian big inn). If we include this globally like in your branch we could safely delete all instances in the buildings helptexts as it is safeguarded centrally which would be good for ading new tribes. Especially taking into account future addons. So as I am not against your proposal I believe the proper fix is to move the format functions where they belong.

**Comment by Noordfrees** [comment]
+1 for cleaning this up. However this is not a trivial change so we should do that for b22. Let's merge the linked PR as the minimal-invasive fix for the nil value, and keep this bug open for b22 as a reminder to clean up the includes.

**Comment by hessenfarmer** [comment]
+1 for cleaning the includes in next release

However I ran a full search over the whole tribes folder for where global_helptexts is included. Only buildings where listed, furthermore a search for the usage of the formtting functions revealed that they are only used in about 15 buildings and I tested them with the moved functions. Therefore I am sure no harm is been done to move the 3 formatting functions to the format_help.lua file.

**Comment by hessenfarmer** [comment]
just saw this would break strings if we move the functions so let's have it this way. But if we need to break strings again before b21 we should fix this porperly as well.

**Comment by gunchleoc** [comment]
I'm refactoring the helptexts in https://github.com/gunchleoc/widelands/tree/pluggable-tribes-helptexts so that message will definitely go away then.

**Comment by gunchleoc** [comment]
The helptext branch fixed this.
