### ISSUE TITLE
Objective messages in scenario savegames keep the language of the game they are created with

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#3966]
If you save a scenario game and restart in a different language the messages keep the original language.   
I believe they should be translated as well, as the rest of the game is translated.   

to reproduce:
open the seafaring tutorial with the language set to anyone you like. after having solved the first objective save and quit. change language to a different one and reopen the game, fulfill the next objective

**Comment by Noordfrees** [comment]
I doubt that it is possible to fix this, because the translation functions are applied once when the script is parsed the first time, and the "compiled" script content is stored in the savegame

**Comment by Noordfrees** [comment]
Related: #1721

**Comment by hessenfarmer** [comment]
not sure as the message mentioned by S-tdh in the other issue is translated in the new locale so there might be a way.
At least we should think about this in b22

**Comment by gunchleoc** [comment]
It is the same problem - these are all assembled strings. The only solution would be to save the complete algorithm and string bits that they were assembled from in the savegame. So, we'd have to save Lua snippets instead of the strings.

I'll mark this as a duplicate, because it is the same problem.
