### ISSUE TITLE
emp04: clicking the farm doesn't register

### ISSUE THREAD

**Issue by s-tdh** [widelands/widelands#4016]
Another small bug: in the fourth scenario of the Imperial campaign, the player has to click a farm after Amalea discovered they're not working well.  However if she/he has other building windows opened (not minimized), opening the farm window does not register.  In this situation, closing the other building windows triggers the next instruction message and the player can move on.  This is entirely unobvious and I suppose it could be frustrating.

As I understand it, which building window that wl.ui.MapView().windows.building_window points to depends on the age and focus of all building windows, right?  It seems this issue can't be fixed in Lua alone.  Would it be reasonable to make all building windows accessible from Lua?

**Comment by hessenfarmer** [comment]
Well, if you opened the farm building window it might take half a second to recognize it due to necessary sleep time. And in the past it should only be triggerable by a farm. but after the latest change of the dismantle button it could as well be triggered by opening the building window of one of the initial foresters. the recognition is done via having a buiding window, without dismantle button, without input wares tab but with workers tab, which was only true for a farm and now is also true for the forester.      
Could you try it again and describe which windows were opened? Just wait half a second after openening the farm. Unfortunately there are no replays in campaigns but you might take a screenshot perhaps.    

For your suggestion see #3226  which I created while working on this feature.

**Comment by hessenfarmer** [comment]
ok I did a short try and it seems that all building windows are evaluated rather then only any one. So here I am at loss, only thing might be to skip the check after 10 minutes rather then reminding about the click.

**Comment by s-tdh** [comment]
I'm patient enough to wait half a second. :)  If someone else wants to reproduce, start the scenario and just wait ten in-game minutes until Amalea asks you to click a farm.  If you click a farm (or indeed a forester) before that, you'll take a shortcut in the mission thread.

Hessenfarmer, why do you believe all building windows are evaluated?  As an experiment, I have the windows for the headquarters and a tower open.  Inspecting the value of mv.windows.building_window.tabs I see names that correspond to one window, if I close it I get the values for the other.  So I think wl.ui.MapView().windows should be changed so that it contains all windows (as the Lua documentation actually promises to :) ), and then the properties you describe in #3226 would be used to search for the right window.  If it's not too much work to implement these Lua bindings, I can't judge that...

**Comment by gunchleoc** [comment]
`static void put_all_visible_panels_into_table(lua_State* L, UI::Panel* g)` only gets the direct children, so we need to make that function recursive.
