### ISSUE TITLE
Alignment errors in tree spritesheets

### ISSUE THREAD

**Issue by Niektory** [widelands/widelands#4237]
Tree spritesheets have misaligned images, with fragments of other images visible on the sides. I think all of them are affected, some more obviously than others.

[Dark Mushroom Tree](https://github.com/widelands/widelands/blob/master/data/world/immovables/trees/mushroom_dark/old_1.png) for example:
![mushroom_dark/old_1.png](https://raw.githubusercontent.com/widelands/widelands/master/data/world/immovables/trees/mushroom_dark/old_1.png)

**Version:**
39d23fe04ecde51128871f0d8dfa850b518923e0

**Comment by gunchleoc** [comment]
I think I exported them before implementing a fix to the cropping algorithm https://github.com/widelands/widelands/commit/be4c07d76d3925c76812fc10839aae1a3ff8785c#diff-aabae7f4b06a763b76c96b390d2ad30c

The issue can be fixed by getting their animation files + code from Build 19 and recreating the spritesheet files.

**Comment by Niektory** [comment]
This seems to work, but there's a lot of them and it's hard to automate because the old lua files don't work without changes. Using an older version for this will probably be easier.
