### ISSUE TITLE
unload expeditions immediately 

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4311]
As ships are loaded and unloadewd at once they should consistently unload their expedition wares at once as well.

See https://www.widelands.org/forum/topic/4911

**Comment by Bjoern2Settler** [comment]
-1

This robs the game a lot of potential and settler feeling

**Comment by frankystone** [comment]
I am unsure about this. When the 'animation' of loading wares was introduced, i found it a bit annoying. But after a while i found it convenient and logical to the fact that loading wares need some time.

When was the animation of loading wares was removed? I didn't noticed it...

The question is some sort of 'type of game': Do we want to be widelands slow-paced, or is there a need of rush? Since widelands has parts which reduce rushing (transport of wares with carriers on roads, probably for a long way) i think this should also apply to ship transporting.

Either ships should load/unload wares at once, or loading/unloading should last some time. Both solutions work and should be consistent, but there should be a consensus of the direction of the game: slow-paced or rushing.

**Comment by Noordfrees** [comment]
Previously, unloading wares was extremely slow (1.5 seconds per ware) but loading wares took place instantly. I changed this in #3857, and the new shipping algorithm assumes that transport ships have no delay at ports. I'd be the last person to turn Widelands from a slow-paced into a rush game, but in my opinion this delay is a detail for which there is no need; which is annoying; and which does not matter with regard to overall game tempo.

In #3880 it was suggested to draw a visible portdock. If this is implemented, we could, if we want, add an animation of wares being transported (at the normal speed of 1.8 seconds per field) from the port to the portdock and vice versa, and only the loading between dock and ship would be instantaneous. (Which would also fix #1444 because port and dock would then be visibly separate units.) What do you think of this?

**Comment by hessenfarmer** [comment]
I totally agree with @Noordfrees 
the unloading was just an additional penalty on ship transport as the wares transport itself takes time. 
So for consistency I am still in favor doing it at once for expeditions as well. 
I didn't recognize the idea with the visible portdock but I really like it

**Comment by Bjoern2Settler** [comment]
But what about the ambiente of the game? If wares and escpecially expeditions are unloaded without any time its not fun watching. Why do we need carriers - because wares are not instantly brought to another building. What about highly important topics in playability like https://www.widelands.org/forum/topic/4981/?page=1#post-34956 since i cant open a pull request to solve these. Great work for build 21 btw, but we need to fix macro before micro.

**Comment by hessenfarmer** [comment]
> But what about the ambiente of the game? If wares and escpecially expeditions are unloaded without any time its not fun watching. 

Well, there is no real animation to watch other then small wares pictograms removed from a ship window. So I can't see the fun in there.    

> Why do we need carriers - because wares are not instantly brought to another building.     

Yep and ships already take their time to sail to a port and to sail to the destination port so this is anything else then instantly.   

> What about highly important topics in playability like https://www.widelands.org/forum/topic/4981/?page=1#post-34956 since i cant open a pull request to solve these. Great work for build 21 btw, but we need to fix macro before micro.   
  
@Bjoern2Settler Stay to the topic please. Regarding pull requests - they are not used to discuss things in general (the forum is the right place for this) - they are used to propose a specific piece of code for review and subsequent merging into master. To get merged there needs to be some kind of consensus.
