### ISSUE TITLE
Dropdown list not responding to mouse move

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4317]
The dropdown's listselect does not respond to mouse moves when the mouse is moving over the hotkey column.

To reproduce: In the main menu, open the SP dropdown, highlight the first entry, move the mouse to the right until it's over the 'N', then move it straight down → doing so should set the highlight and tooltip to a lower entry, but the highlight remains on the first line and the tooltip always says "Begin a new game".
![wl-dropdown-issue](https://user-images.githubusercontent.com/48293446/94839801-cb823880-0417-11eb-9197-5bcf8036fab7.png)

**Comment by matthiakl** [comment]
The problem is not the hotkey column, but a fix offset from the right, where the selection started.
This can be observed in all dropdown menus and I suspect the push button to cause problems.
![Bildschirmfoto vom 2021-05-20 21-12-29](https://user-images.githubusercontent.com/23122583/119035889-5f594280-b9b0-11eb-8c46-4e5dda78cbb6.png)
![Bildschirmfoto vom 2021-05-20 21-17-09](https://user-images.githubusercontent.com/23122583/119036784-6e8cc000-b9b1-11eb-8055-ef3171f3f0bd.png)
