### ISSUE TITLE
New in-game music song

### ISSUE THREAD

**Issue by pospec4444** [widelands/widelands#4352]
I've found this YouTube channel which lists a lot of OC fantasy/medieval songs:
https://www.youtube.com/c/DerekBrandonFiechter/videos

My ears told me that some songs might fit already existing in-game music. I asked authors of the music and they agreed that we might use one or two songs if we want to.

I'm willing to coordinate this activity with them.

At the moment, I'm trying to pick some songs which would fit best.

[Playlist with my picks](https://www.youtube.com/playlist?list=PLAWnqaFK7Lg8-eNqO5X94jImzlqYg6zsu)

**Comment by frankystone** [comment]
Didn't listen to the music (i hate youtube)...

You should ask on which License they want to share their music. Since widelands [license](https://github.com/widelands/widelands/blob/master/COPYING) is GNU general public license, any content can be copied, reworked and also sold, afaik. Of course always under the same license (GNU general public).

**Comment by pospec4444** [comment]
GNU won't work for them.
