### ISSUE TITLE
Nightly builds on Mac OS broken due to tests failing

### ISSUE THREAD

**Issue by SirVer** [widelands/widelands#4413]
Starting today (2020-10-26) nightlies fail to build due to test failures in test_economy:

```
Test project /Users/sirver/Desktop/Programming/cpp/widelands/widelands.build
    Start 1: test_ai
1/5 Test #1: test_ai ..........................   Passed    0.69 sec
    Start 2: test_economy
2/5 Test #2: test_economy .....................***Failed    0.27 sec
Running 21 test cases...
unknown location:0: fatal error: in "Road/PassabilityTest": FileNotFoundError: FileSystem::create: could not find file or directory: /Users/sirver/Desktop/Programming/cpp/widelands/data
/Users/sirver/Desktop/Programming/cpp/widelands/git_repo/src/economy/test/test_road.cc:93: last checkpoint: "PassabilityTest" fixture ctor
unknown location:0: fatal error: in "Road/CorrectSizeTest": FileNotFoundError: FileSystem::create: could not find file or directory: /Users/sirver/Desktop/Programming/cpp/widelands/data
/Users/sirver/Desktop/Programming/cpp/widelands/git_repo/src/economy/test/test_road.cc:96: last checkpoint: "CorrectSizeTest" fixture ctor
unknown location:0: fatal error: in "Road/InstantiateEditorGameBase": FileNotFoundError: FileSystem::create: could not find file or directory: /Users/sirver/Desktop/Programming/cpp/widelands/data
/Users/sirver/Desktop/Programming/cpp/widelands/git_repo/src/economy/test/test_road.cc:99: last checkpoint: "InstantiateEditorGameBase" fixture ctor

*** 3 failures are detected in the test module "Economy"


    Start 3: test_io_filesystem
3/5 Test #3: test_io_filesystem ...............   Passed    0.24 sec
    Start 4: notifications_test
4/5 Test #4: notifications_test ...............   Passed    0.19 sec
    Start 5: test_scripting
5/5 Test #5: test_scripting ...................   Passed    0.03 sec

80% tests passed, 1 tests failed out of 5

Total Test time (real) =   1.42 sec

The following tests FAILED:
	  2 - test_economy (Failed)
```

The current sha is d79d65d7e6e8fa3d80315c1ef0d36b555745a31b. 

I have not investigated, I hope somebody has an idea what that could be about. @gunchleoc maybe?

**Comment by SirVer** [comment]
It is true that the datadir is not at `/Users/sirver/Desktop/Programming/cpp/widelands/data/`, but instead at `/Users/sirver/Desktop/Programming/cpp/widelands/git_repo/data/`, but I have not changed anything since the last successful build on the build environment and it started failing on both of my build machines at the same time.

**Comment by gunchleoc** [comment]
To fix this, add the datadir you need to `src/economy/test/test_road.cc` in the contructor of `struct WlTestFixture`. I hacked it in there for Linux, because the homedir is complete nonsense there.

This is needed to load `TribeBasicInfo` now.

The change is cause by https://github.com/widelands/widelands/commit/d79d65d7e6e8fa3d80315c1ef0d36b555745a31b

**Comment by hessenfarmer** [comment]
I get the same error as I do not build in the repo directory as well. I usually build in a different directory due to minimising the risk of affecting the repo. 
If the datadir is necessary to load something in the test it might be good to code the path to the src (repo) datadirectory and start the test exe with the datadir option
