### ISSUE TITLE
Build-21 won´t start

### ISSUE THREAD

**Issue by uerlings** [widelands/widelands#4453]
I´ve installed build-21 64bit (and 32bit also) 
[stdout.txt](https://github.com/widelands/widelands/files/5469820/stdout.txt)

on Windows 10 and the following error message appears:

ERROR: Widelands won't work because we were unable to detect the shading language version.
There is an unknown problem with reading the information from the graphics driver.

OS: Windows 10 Pro version 1909  18363.1139
CPU: Intel i%02450M 2.5GHz
RAM: 6 Gb

Attached stdout.txt

**Comment by Noordfrees** [comment]
According to the stdout your graphics card or driver provides OpenGL at version 1.1.0. Widelands needs at least version 2.1. Please try upgrading your graphics driver to see if you can get a higher OpenGL version.

**Comment by Noordfrees** [comment]
See also https://www.widelands.org/wiki/Technical%20FAQ/#why-wont-widelands-start-after-upgrading-to-windows-10-on-my-computer
> Widelands needs OpenGL Version >= 2.1. This seems to be a known issue on Windows 10 with some graphics cards due to the lack of a good graphics driver, see for example https://communities.intel.com/thread/78542.

**Comment by frankystone** [comment]
The best thing we can do is to show a hint, probably during installation, that the current graphics driver don't fit to run widelands. But i don't know if it is worth the work:

1. make a small program which checks OpenGL and the capabilities of the graphics driver
2. [Run this program within Innosetup](https://stackoverflow.com/questions/3493416/how-to-run-a-file-before-setup-with-inno-setup) and if the return codes doesn't match, expose it to the user.

I am in favor to close this bug because it is not an issue of widelands.

**Comment by hessenfarmer** [comment]
+1 for closing the bug 
+1 for checking the graphics in the installer (innosetup) if this is possible.  Alternatively improve the failure message once again to tell it might be a graphics driver problem instead of being a problem in reading from  it

**Comment by gunchleoc** [comment]
We should add another error message for the OpenGL version, just like we did for the shading language
