### ISSUE TITLE
Ship sails to other port than target

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4534]
In the attached save game i have cancelled an expedition. In result the ship sails to another port than shown when clicking "Go to destination" ("Gehe zum Ziel") in the ships window.

**To Reproduce**
1. Load the save game [test.zip](https://github.com/widelands/widelands/files/5581555/test.zip)
2. Wait until the ship named "Faustulus" comes into view. This is the ship where the expedition was cancelled.
3. Open the ships window
4. Click on "Go to destination" ("Gehe zum Ziel")
5. But the ship sails first to the port in the first view without unloading the expedition wares, not to the destination shown when clicking "Go to destination".

**Expected behavior**
The ship should sail to the destination shown when clicking "Go to destination". Or the destination should be the port the ship sails at first and unload the expedition wares at this port.
When cancelling an expedition, maybe the ship should go the nearest port?

**Version:**
 - OS: archlinux
 - Widelands Version: [a3ffba3@master] (Release) 

**Additional context**
I guess this happens because ships are ever sailing around also if they are empty. For me this behavior is very annoying.

**Comment by frankystone** [comment]
The save game from #4532 shows that clicking "Go to destination" in a ships window does not work for many ships. So cancelling an expedition is not the real issue.

**Comment by Noordfrees** [comment]
The reason is that the paths between ports are cached for performance. When a ship wants to sail from port A to port B, it will simply look up the cached path from A to B. For this purpose the ship always remembers both its current destination (B) and the last dock it ever visited (A).

When you cancel an expedition, the ship is told by the fleet to go to some well-suited port – in this case the one on the south of Spain. But the ship's lastdock is still the one in India. Since the ship's current position is nowhere near the cached path from India to Spain, the ship now needs to sail to an arbitrary location on the cached route before it can sail to Spain. This is very performance-hungry, so the closest spot on the cached route is chosen. So the ship needs to sail to a spot close to the indian port before being able to use the cached route to go to its allotted spanish destination.

This only happens when a ship is away from any cached route *and* the lastdock happens to be the closest spot on the lastdock<->destination route, which only happens *sometimes* in the context of expeditions, and rarely when a port is destroyed. I am in favour of closing this bug as wontfix.
