### ISSUE TITLE
Wrong militarysite soldier statistics strings

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4537]
In this screenshot the milsite displays the wrong soldier info: It says there are 0 soldiers present but in fact 1 soldier is inside.
![shot0002](https://user-images.githubusercontent.com/48293446/100363634-51c49080-2ffd-11eb-88b2-6475722b48ee.png)
[Savegame](https://github.com/widelands/widelands/files/5603589/soldierstatsbug.wgf.zip)

**Comment by matthiakl** [comment]
Could not reproduce with current master. I loaded the savegame and pressed page down during load, so the game started paused. The string showed correctly 1(+1). Did you verify, that the problem persists after loading it from save?

**Comment by Noordfrees** [comment]
Seems like this bug indeed vanishes after saving-reloading. I saw this problem several more times recently in master though.

**Comment by frankystone** [comment]
There is definitely something wrong with this and i saw wrong strings often. I guess it has something to do with exchanging soldiers.

Play around with with the Barbarian fortress in this save game:

1. Wait until one soldier is leaving -> String shows 7 (+1)
2. then reduce the amount of soldiers by one -> A Soldier is leaving. I would expect that the empty slot will be closed. The string shows now 6 (+1), which is correct because a soldier was leaving and the empty slot is not closed.
3. then set amount to 8 again -> String shows 6 (+1) but should show 6 (+2)

[test.zip](https://github.com/widelands/widelands/files/5868337/test.zip)
