### ISSUE TITLE
Add ons; Provide information on the maps download page

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4548]
It would be nice if the maps download section on the homepage shows with which addon a map was made.

**Implementation steps**
- [ ] Expose the addon name to the  json file created by wl_map_info

The other step is then on the website code.

**Comment by Noordfrees** [comment]
I am in favour of prohibiting them on the maps upload page and asking people to make an add-on instead. I am going to write a utility to package your own maps as an add-on fully automatically from inside the add-on manager, and downloading maps as add-ons means much easier dependency handling for everyone who wants to use the map.
The wl_map_info executable currently throws an error ("ERROR: This map depends on add-ons!") if a map uses add-ons, so the website would only need to refuse the upload in this case.

**Comment by frankystone** [comment]
> I am in favour of prohibiting them on the maps upload page and asking people to make an add-on instead.

On the long run this means every new map will then be an addon, imho. And this means one has to fiddle with the addon system just to play a map. Not sure if this a good goal.

**Comment by frankystone** [comment]
Don't know if it would be possible, but i think implementing an addon inside the map would be better. An addon is then part of the maps file structure. Starting such a map wouldn't need to activate or use addons at all.

This would be much easier for new players and map designers, imho.

**Comment by Noordfrees** [comment]
Well currently anyone who wants to download a map needs to visit the homepage (if they even know that it exists and offers free maps for download), discover where their WL home directory is located, and download and move the map. Being able to do browse maps inside Widelands with three clicks (Add-Ons → Browse → Map Sets) and installing with another two (Install → OK) is much more convenient surely?

To play a map downloaded like this, you don't need to fiddle with anything apart from the installation of the map itself: The required add-ons are selected for you automatically whenever you start a game; and if some requirements are missing, the add-ons manager offers a button "Fix dependencies" that takes care of all issues automatically – but only if you installed the map as an add-on; it is for maps downloaded manually from the website that you need to fiddle with the add-ons system to manually search and install the required add-ons.

So I think that for maps using add-ons, the distribution via the add-ons server is much more user-friendly than via the website. (In the long run, this is also the case for *all* maps btw…)

---

Integrating the add-on in the map's file structure would not make sense because the map file needs to be located in the add-on's directory rather than the other way around…

**Comment by frankystone** [comment]
Your approach is straightforward. I am just a bit overwhelmed by this new feature and the ui ;)
