### ISSUE TITLE
MP Scenario Setup: Glitch with Player Type Dropdown

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#4664]
**Describe the bug**
The type dropdown in the MP setup for a scenario map can turn inaccessible during the setup and contains invalid entries.

**To Reproduce**
Steps to reproduce the behaviour:
1. LAN → New Game → Choose map 'Trident of Fire'
2. Set the first player's type to Normal AI. The button to change the type is still enabled, as it should be.
3. Set your own player number to player 2. Now the first player's type dropdown is suddenly disabled so you can no longer change player 1's AI type.

**Expected behaviour**
If I remember correctly, it used to be forbidden to use AIs or to close a slot for MP scenario maps. The respective dropdown entries should be removed, and the dropdown's enabled state must be consistent with the normal MP setup.

**Version:**
 - OS: Ubuntu MATE 20.10
 - Widelands Version: 1.0~git25155[c201ec1@master] (Release)

**Comment by matthiakl** [comment]
The exact same behavior was already present in build 21, so no regression here. 
I'm not sure about disallowing AIs and closed slots in the selection. In 'Trident of Fire' non-human players are replaced by AIs, so these cases are handled by the scenario (a rule?). 
The "shared in" option clearly does not work because of the tribe presets, so this should be disabled. And the disabled dropdown  should also be fixed.
Additionally, I noticed that a joining player always overrides the first non-player slot, regardless whether it is closed or an AI.
And the type dropdown items are not translated initially, only after some roundtrips between the client and host (e.g. client selects a slot).
