### ISSUE TITLE
SoundHandler: Sound effect xy does not exist!

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4676]
When saving a map the console prints endlessly:
~~~~
[00:54:08.273 real] ERROR: SoundHandler: Sound effect 12 does not exist!
[00:54:08.273 real] ERROR: SoundHandler: Sound effect 11 does not exist!
[00:54:08.273 real] ERROR: SoundHandler: Sound effect 9 does not exist!
[...]
~~~~

**To Reproduce**
1. Start editor and load map Kings and Queens
2. Save it

I got this endless prints also if i had create a new map and placed some critters, but i can't reproduce it this way.

**Version:**
 - OS: archlinux
 - Widelands Version: [ddcc509@3849_win_conditions] (Debug)

**Additional context**
A similar bugreport was #4258 but this was after saving a game.

**Comment by matthiakl** [comment]
I think the culprit is here:
https://github.com/widelands/widelands/blob/86674946dcbc5a1024a3edf197b0fdc3ff1ada49/src/logic/map_objects/descriptions.cc#L119-L123
During loading and saving the descriptions are instantiated multiple times. When the save window is closed, sounds are removed from the global sound manager without readding them somewhere else.
