### ISSUE TITLE
Thoughts on options menu

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4733]
> The Interface and Window tabs of the options menu were merged recently because the tab row got too wide, so it > seems rather cluttered now. Suggestions how to unclutter it without adding more tabs welcome…

_Originally posted by @Noordfrees in https://github.com/widelands/wl_addons_server/issues/23#issuecomment-786811833_

Edit: Will ad some of my thoughts in the next days

**Comment by frankystone** [comment]
Tab _Interface_:

- Do we need the dropdown 'Windowsize' anymore? Since the main windows can be resized?
- Do we need ' Use system mouse cursor'?
- Do we need 'Maximum FPS'? I guess no one has ever changed this.
- What effect has 'Accessibility mode for Tooltips'? If i enable it, one tooltip of the main  menu stays open although the mouse moves to another button. Bug?
- The options related for docking and snapping windows should be grouped with the related settings (red marked):
![dock_snap_options](https://user-images.githubusercontent.com/6730556/109782832-9d449700-7c09-11eb-8f43-c84f0c195cf7.jpg)
- Move 'Animate automatic map movements' to the In-Game tab? This would solve the previous point.

The 'Edit keyboard shortcuts' is fine here i think.

**Comment by frankystone** [comment]
Tab _'Sound'_:

Just a suggestion here: Invert position of checkboxes and sliders:

![options_sound](https://user-images.githubusercontent.com/6730556/109785614-95d2bd00-7c0c-11eb-8f08-e47a2732e1c2.jpg)

**Comment by Noordfrees** [comment]
> Tab _Interface_:
> 
>     * Do we need the dropdown 'Windowsize' anymore? Since the main windows can be resized?
> 
>     * Do we need ' Use system mouse cursor'?
> 
>     * Do we need 'Maximum FPS'? I guess no one has ever changed this.

I use Windowsize a lot because different window sizes are useful when debugging stuff in several windows. It's so much more convenient that manual resizing. 
Use system mouse cursor needs to be an option because this feature can cause bad glitches on some hardware or drivers. 
I set MaxFPS much higher than default for smoother performance, but I'd be fine with making this one of the "hidden" options (accessible only from commandline or manual config file editing).

>     * What effect has 'Accessibility mode for Tooltips'? If i enable it, one tooltip of the main  menu stays open although the mouse moves to another button. Bug?

That's the point of this setting. It freezes all tooltips in place so you can keep reading them while moving the mouse away, which would be impossible otherwise for users of eye-tracking devices.

>     * The options related for docking and snapping windows should be grouped with the related settings (red marked):
> 
>     * Move 'Animate automatic map movements' to the In-Game tab? This would solve the previous point.

+1

**Comment by matthiakl** [comment]
The language hint should span over all three dropdowns instead of just the top two:
![Bildschirmfoto vom 2021-03-05 20-04-41](https://user-images.githubusercontent.com/23122583/110161725-0d137700-7dee-11eb-911f-e7d548047d62.png)

>Tab 'Sound':
Just a suggestion here: Invert position of checkboxes and sliders:

+1

**Comment by Noordfrees** [comment]
The Theme dropdown will be removed again in #4734

**Comment by Noordfrees** [comment]
- Does anyone have Mouse Grab turned on? If not, we could consider removing that option.
- Do we need the Write Syncstreams checkbox? Desyncs are rare now, and I for one find it much easier to define the `SYNC_DEBUG` symbol at compile-time instead of bothering with syncstream files, so a command line switch would be sufficient IMHO.

**Comment by klaus-halfmann** [comment]
+1 for making the sync-streams a commandline option
+1 for FPS 
+1 for Mouse Grab 

I used the window-size via commandline for some youtube videos only. 
It can be importat if you last played WL on a big, external screen an now 
start without it. Not sure how bad this is for the average player.

The cluttering is worse in german as we need longer texts there.
But we should check other languages, too

**Comment by frankystone** [comment]
Can't `max FPS` not be set automatically? Or set it to a higher value by default. I set it now to "99" and started a big save game. The FPS showed during the game are round about "70" and AVG shows values between 40 and 57.

**Comment by gunchleoc** [comment]
> Do we need the dropdown 'Windowsize' anymore? Since the main windows can be resized?

Might be useful for streamers to be able set the window at a well-defined size.

**Comment by frankystone** [comment]
To sum this up:

Interface tab:

- [ ] Move "Animate automatic map movements" to the In-Game tab
- [ ] Remove "Grab Input"
- [ ] Remove "Maximum FPS:" and hardcode a higher value
- [ ] Give the translation stats more vertical space

Sound tab:

- [ ] Invert position of sliders and check boxes

Saving tab:

- [ ] Remove "Write syncstreams" and make this a command line option

**Comment by tothxa** [comment]
> Remove "Grab Input"

Can the whole `set_input_grab()` function be removed with it?
