### ISSUE TITLE
Kicking a worker let him go the building where he was kicked off

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#4809]
I have noticed this behavior several times now.

If you have two buildings A and B which uses the same worker, probably far away from each other.
A has a worker, B misses a worker.
Kicking the worker from A let him mostly not go to B. Instead the worker leaves the building to the buildings flag and then he goes immediately back to A again.

I noticed this for master miners and the empire stonemason which is used by a quarry and a stonemasons hut. The only solution i found was to cut off the roads from the building before kicking the worker... and pray that the worker finds a flag nearby :-)

In the attached game try to kick the worker from the quarry to let him go to the stonemasons house. Sometimes it works, sometimes not. Mostly it doesn't work if the stonemason is inside the quarry.

**Expected behavior**
The building where the worker get kicked out shouldn't request the worker again. At least not immediately.

**Version:**
 - OS: archlinux
 - Widelands Version: [296b275@master] (Debug)

[kick_the_stonemason.zip](https://github.com/widelands/widelands/files/6305455/kick_the_stonemason.zip)

**Comment by Noordfrees** [comment]
What happens internally is that a building that lacks a worker opens a Request for the worker, and the economy assigns an available worker to a matching Request. All worker requests have medium priority (there's no UI to change this ATM), so the two deciding factors when matching supplies to requests are how long the request has been open and the walking-time distance of the request-supply pair. Effectively this means that requests are fulfilled first-come-first-served, with exceptions made if a new request is very close to the available supply and the older requests are very far away.

This bug is a side-effect of the described optimization. IMHO the best way to fix it would be to add a high penalty to a request-supply pair's score if they are less than a very low threshold (3.6 seconds or such) apart and the request has been opened very recently (e.g. less than 10 seconds ago). This should probably catch all such cases without too many erratic hits in other situations.

https://github.com/widelands/widelands/blob/296b275983ef794423a5bff743b223a56d64d04b/src/economy/request.cc#L300-L311

**Comment by klaus-halfmann** [comment]
I have seen the same Problem with Amazones "Jungle Masters" and "Master Woodcutters". Especially annyoing is, that I can not move a weill trained Jungle Master to a "Rare Tree" plantation or a "Gardennig Center" and they remain unoccupied for some time until I notice, much later. So In addition of your (reasonabale) fix: Could we kick out well trained workers out to get new workers in for training? Like we do with Soldiers in Military training sites. But maybe this will not help experienced players?

**Comment by Noordfrees** [comment]
Most of the time this already happens. When you kick an experienced worker from a slot that requires as minimum a less experienced one, the engine first tries to look for suited candidates elsewhere (and usually chooses or newly creates a worker of the low-experience type), and only if this fails because you have no such workers nor the required tools, then the kicked worker is also considered. (This is due to the fact that the kicked worker is only registered as "available for requests" upon reaching the building's flag, but not during the 1.8 seconds it takes him to get there, whereas the economy already starts looking for a replacement during this time). 
So if the means to create a new worker are available then this is already preferred, and only if there's a shortage of the tools you need then this will not work.

**Comment by hessenfarmer** [comment]
A shortage of tools can happen very easily.     
Furthermore the linked code does only tke ware priorities into account. does this work for workers as well since we split the ware economy from the worker economy?
Open slots for experienced worker should have higher priority imho.
As this is affecting our new tribe amazons very heavily we should reconsider fixing this for 1.0

**Comment by Noordfrees** [comment]
A true fix would be overkill so shortly before a release but I have an idea for a workaround

**Comment by Noordfrees** [comment]
IMHO the fix can be considered good enough to be permanent. IIRC I left a TODO to beautify it on occasion, but we can close this bug.

**Comment by frankystone** [comment]
This happens again, see https://www.widelands.org/forum/topic/5830/

I had this issue also in my last tournament match.
