### ISSUE TITLE
Website Encyclopedia misses upgrade building costs

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#4969]
In the Website encyclopedia the buildcost for upgraded Buildings are not shown anymore. 
need to check the in game version.    
the culprit is most probably the shift of the Build costs to the enhanced building.

**Comment by hessenfarmer** [comment]
closed as it is a website bug only

**Comment by frankystone** [comment]
As far i remember the buildcost for upgraded buildings (buildcost which needs a building for upgrading) wasn't there for years. See e.g.: https://github.com/widelands/widelands-website/issues/132#issuecomment-527968311

The reason is that this info (beside some other infos) isn't extracted by wl_map_object_info. E.g.: the extracted info for an empire barrier (which can be enhanced form an outpost) is:
~~~~
      {
         "name": "empire_barrier",
         "descname": "Barrier",
         "icon": "tribes/buildings/militarysites/empire/barrier/menu.png",
         "enhanced": "empire_outpost",
         "conquers": 8,
         "max_soldiers": 5,
         "heal_per_second": 130,
         "type": "militarysite",
         "size": "medium",
         "helptext": "Garrisons soldiers to expand your territory.",
         "buildcost": [
            {
               "name": "log",
               "amount": 2
            },
            {
               "name": "granite",
               "amount": 2
            },
            {
               "name": "planks",
               "amount": 2
            },
            {
               "name": "marble",
               "amount": 1
            }
         ]
      },
~~~~

So i would suggest to reopen this issue (for the needed changes to wl_map_object_info) and leave https://github.com/widelands/widelands-website/issues/362 also open.

**Comment by frankystone** [comment]
Initially the idea of the website encyclopedia was to give the player some sort of help. It was created before the in game help was available. And i remember also that on the long run the website encyclopedia should be fully replaced by the ingame help (which i think is the better way). Nevertheless it can be helpful for scripting.

So all in all i am unsure if the buildcost for upgraded buildings is really needed on the website.
