### ISSUE TITLE
Rare Tree Plantation help

### ISSUE THREAD

**Issue by MXB2001** [widelands/widelands#4981]
**Is your feature request related to a problem? Please describe.**
The problem is that the most efficient way to run a tree planter used to be to remove the road to his hut once he arrives. This screws up the rare tree planter though since he's not in the economy anymore and doesn't plant rare trees as needed.

**Describe the solution you'd like**
A BIG NOTICE in the help for this building to tell new players to always make sure it has a road connected.

**Describe alternatives you've considered**
Posting to the forums but not everyone reads them.

**Additional context**
n/a

**Implementation steps**
1. Edit the help text
2. Done ; - )

**Comment by alasiax** [comment]
Ok, I was thinking to update the text on this, but actually, the plantations do keep working when disconnected, but they don't adhere to main economy targets and instead plant indefinitely because each flag has its own economy. For example, say your main economy only needs rubber, your plantations will still keep planting the trees in the balsa/rubber/ironwood sequence, not being aware that actually the main economy might be saturated with ironwood and balsa.

This can be used to fine tune your plantations - for example, the plantations near your dressmakery could be set to 0 for ironwood, or conversely to 0 for balsa and rubber near the stone workshop.

**Comment by alasiax** [comment]
On reflection, it was pointed out to me that it would be appropriate to have an Amazon tip, and a note in the building about that the mechanics work as designed, and why disconnecting roads to plantations will create infinite plantings, without respecting the economy targets as defined by the warehouses rather than the economy of each disconnected plantation.

**Comment by alasiax** [comment]
I have added tips and building help text to address this issue, and submitted it for commit :o) Please let me know if more is needed. (I'm Alasia on the WL forum if that's easier)
