### ISSUE TITLE
Empire2: cannot complete barracks

### ISSUE THREAD

**Issue by MPagel** [widelands/widelands#5043]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
In empire campaign mission "An Outpost For Exile" cannot complete barracks due to lack of cloth.  Neither weaving mill nor sheep farm appear in build menus.

**To Reproduce**
Unknown.  My only current objective is labelled "Destroy the Barbarians".  The first bullet point is to build a barracks. 

**Expected behavior**
Cloth-related buildings should have been unlocked long ago (same time as piggery? donkey farm?)

**Screenshots**
Screenshot below.

**Version:**
 - OS: Windows 10
 - Widelands Version: 1.0 (release)

**Comment by MPagel** [comment]
![WidelandsNoCloth](https://user-images.githubusercontent.com/3179116/131023157-5f93da87-9a4d-4c66-a4f6-e596eabf8d25.jpg)

**Comment by MPagel** [comment]
I was able to sack the enemy HQ and take all military buildings, but as the barracks does not exist on my side, nothing else triggers after obliterating the enemy.
[fsdfseffadgag.zip](https://github.com/widelands/widelands/files/7062310/fsdfseffadgag.zip)

Savegame at end included

**Comment by hessenfarmer** [comment]
the problem is not the missing barracks, but the missing fortress on the former Barbarians peninsula.  
Furthermore to complete the mission the baracks could be completed by reducing the cloth input to the amor smithy.    

Anyhow you are right if we allow a barracks we should allow sheep farm and weaving mill.  Will be corrected
