### ISSUE TITLE
Atlantean tower is set to weak soldiers by default

### ISSUE THREAD

**Issue by spth** [widelands/widelands#5044]
Usually, larger military buildings default to strong soldiers, while small ones default to weak soldiers. However, the Atlantean tower is an exception, as it is the Atlantean's second-strongest military building, but defaults to weak soldiers. I guess that this is a mistake, rather than a design choice.

**Comment by hessenfarmer** [comment]
It seems the settings of the small tower and the tower got mixed. So I would vote for having the tower prefer heroes and the small one not to do so.

**Comment by alasiax** [comment]
+1 for what @hessenfarmer said, will correct shortly.

**Comment by alasiax** [comment]
Edit: I deleted the PR for this as I think it needs further discussion.

For consistency, maybe have one medium plot building for each tribe (the lower, heightwise with less vision) which prefers rookies, and the tower equivalent which prefers heroes. Most tribes have upgrades available to medium plot buildings, but I think only Empire can access the upgrade in the plot build menu. 
For comparison, at the moment: (Edit: error correction)
Barbarians  - Barrier (h)         Tower (h)     
Empire       - Outpost (r)        Barrier (h)   Tower (h)        
Atlanteans - Guardhall (h)     Tower (r)     High Tower(h)*    
Frisian       - Outpost  (h)        
Amazon    - War. Dwell.  (h)  Tower (h)    Obs Tower(r)*   

\*available only via upgrade, not plot build, so rookie/hero setting is irrelevant as it inherits the foundation preference as far as I can tell.

For Atlanteans, they also have small plot towers - the guardhouse is rookies, and small tower on small plot is advanced. So the original makes sense to have small tower prefer heroes. 

For Amazon and Atlantean, I would argue for the higher towers to be in the plot build list, with tower set for rookie, and high/obs tower to heroes. Otherwise, Guardhall and Warrior Dwelling for rookies and towers for heroes. This way, for all tribes, highest tower = heroes, which is better consistency for players.

Unfortunately this logic is not easily applied to barriers - I'd argue for barriers having rookies by default for Barbarians, but as it's an upgrade for Empire, that would be inconsistent.

**Comment by hessenfarmer** [comment]
thanks for the list. However there is a small error as amazon tower prefers Heroes and the obs. Tower prefers rookies. I need to check though whether the setting is inherited from the base which is a bug in this case imho that was introduced with the feature to keep the settings. I believe the logic is more simple. Heroes prefer space and company so only buildings with at least 4 soldiers should prefer heroes.  this excludes small buildings which is correct imho. So the 2 Atlantean towers and the amazon observation tower should be changed from my point of view.

**Comment by alasiax** [comment]
Yes, you are right - the small tower wants heroes. I'll edit the above for clarity.

So, other than the Empire outpost, all medium+ militaries should prefer heroes then?

**Comment by alasiax** [comment]
Comparison below, based on heroes going by default to buildings of 4+ soldiers.

**Current:**
Barbarians - Barrier (h) Tower (h)
Empire - Outpost (r) Barrier (h) Tower (h)
Frisian - Outpost (h)
Amazon - War. Dwell. (h) Tower (h) Obs Tower(r)*
Atlanteans - Guardhall (h) Tower (r) High Tower(h)*
Atlanteans - Small Tower (h) (small plot)
\*available only via upgrade, not plot build

**Proposed:**
Barbarians - Barrier (h) Tower (h)
Empire - Outpost (r) Barrier (h) Tower (h)
Frisian - Outpost (h)
Amazon - War. Dwell. (h) Tower (h) Obs Tower(**h**)*
Atlanteans - Guardhall (h) Tower (**h**) High Tower(h)*
Atlanteans - Small Tower (**r**) (small plot)

**Comment by hessenfarmer** [comment]
the proposed table is what I would deem appropriate.    
regarding the availability from the build menu. This would only make sense if buildcost for upgrade would differ from direct build which in turn would make especially the atalntean high tower to cheap. so I don't think we should change it. Since b21 it is possible to directly upgrade the constructionsite anyway.
