### ISSUE TITLE
Resolve asan testsuite issues

### ISSUE THREAD

**Issue by matthiakl** [widelands/widelands#5100]
Re #5090 
The testsuite reports some asan issues which should be addressed. See [this log](https://github.com/widelands/widelands/runs/3988961420?check_suite_focus=true)

Since leaks are suppressed all together in the CI, the testsuite should be run on a local machine to see, whether some leaks can be resolved as well.

**Comment by Noordfrees** [comment]
Interestingly the failure always seems to happen on just three configurations: g++ 5 and 6 under Bionic; both release builds plus the g++6 debug build.
I'm compiling Widelands in a Bionic container now to look at it…

---

It's reproducible with g++5 under bionic in the Casern test. Will investigate.

**Comment by Noordfrees** [comment]
The bug seems to be in `boost::format` (specifically I'm using version `1.65.1.0ubuntu1` there). 

Rewriting this function:
https://github.com/widelands/widelands/blob/9efa8ea23bee95cf33fcef5a07c3d526d4ad4d60/src/graphic/style_manager.cc#L385-L390
to use plain string concatenation instead of `boost::format` fixes this crash, only to get a new crash a second later elsewhere (in `as_mapobject_message`) as we use `boost::format` a lot. Gotta love this library, we never have any sort of problems with it whatsoever, oh no…

#5081 gathers 99% of our `boost::format` calls in a single `bformat` interface function. From there it's only a small(ish) step to ripping it out completely, which I would consider the most *desirable* approach to fixing this bug.

---

Edit: To clarify, the testsuite with ASan shows multiple bugs, of which several but not all are boost-related. They should best be addressed one by one until all checks are green.
