### ISSUE TITLE
Widelands Version String Generates Erratic Markdown

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#5136]
Development versions of Widelands have the format
```
versionnumber ~ revision [ commit @ branch ] ( buildtype )
```
e.g.
```
1.1~git25529[fe7992d@master] (Release)
```
Unfortunately, when posting something containing `[hello](world)` in a Markdown-interpreted form (e.g. a GitHub issue or the forum turns this into a link to `world` displayed as `hello`. This makes the pasted version string much harder to read, and on GitHub it additionally prevents GitHub from automatically linkifying the commit hash (as in: fe7992d). This does not happen if there's a whitespace between `]` and `(`, but the version string is inconsistently displayed sometimes with and sometimes without this whitespace.

I propose to change all occurrences of this version string formatting to use different characters that are never interpreted by Markdown even if some whitespace is added or removed, for example by replacing the `()` with `[]` or vice versa or using `{}/$%+#`. While doing this it should also be made consistent everywhere.

Technically, only the part `1.1~git25529` is the actual version number (used for version comparison in packages and releases); everything after this is just extra formatting for display which we can modify freely.

**Comment by matthiakl** [comment]
My suggestion is to remove the `()` around the build type and use them for the branch info instead: 
`1.1~git25529 (fe7992d@master) Release`
I also had the idea to reorder the string, to have the explicit version info in front and the additional git info afterwards, but I guess this is not feasible, since the build type is evaluated later: 
`1.1~git25529 (Release) [fe7992d@master]`

**Comment by Noordfrees** [comment]
Marking as urgent for v1.1 because an open PR is linked.
