### ISSUE TITLE
Disabled addon cause GameDataError but the error can be tricked out

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5180]
The attached map was made with the add-on no_default_resources.wad.

1. If the addon is installed but disabled and one tries to load the map (Hotkey `b`), the open map dialog shows a Game Data Error but no conflicts with the addon: 
![game_data_error](https://user-images.githubusercontent.com/6730556/147833413-cd1fea16-6c5b-4d73-889a-ea82e89fd00a.jpg)
The map can't be loaded and it is difficult to understand what the problem is (the disabled add-on).
2. Loading the Map from the main menu (Hotkey `w`) works without problems, although the addon is disabled (To test it: Enable addon, load the map, save the map, close editor, disable addon and hit `w` in the main menu). The Editor works fine, one can set terrains without default resources, save the map. Obviously the Error from 1. has no meaning?

**Expected behavior**
Loading the map should either work or not. Either show the "Game Data Error" (probably with a hint about disabled add-on) when loading the map via `w`, or disable the "Game Data Error" when loading via `b`.

**Version:**
 - OS: archlinux
 - Widelands Version: 1.1~git25596[7d637a3@diplomacy] (Debug)

[Hilly.zip](https://github.com/widelands/widelands/files/7796700/Hilly.zip)

**Comment by Noordfrees** [comment]
Ouch, not trivial. When the dry barren summer steppe registers the dry summer steppe as its enhancement, a Notification is published to ensure that the enhancement is a valid and loaded terrain type. This Notification is sent to *all* `Descriptions` instances *every one of which* performs this check. When we load a map "normally" (e.g. via <kbd>W</kbd>), there is only 1 `Descriptions` instance so this is fine. In the saveloading window however there are two – one for the game/editor in the background, and one for a pseudo-game/editor which holds temporary information about the map/game we want to show in the saveload window's right column. The latter has all the correct add-ons loaded, the former does not. Somehow we need to ensure that the Notification only reaches the one Descriptions instance for which it is intended.

---

(That you can load a map when a required add-on is disabled is by design – your add-on settings are effectively ignored here and changed just for the one game/editor session to match the map's requirements.)
