### ISSUE TITLE
Fail to select Ship in Neptunes Revenge

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#5200]
**Describe the bug**

When playing Neptunes Revenge I got stuck as I was unable to select the Expedition ship.
Minerva. As a workaround I later found that I can use the Ships statistics Window, too.

**To Reproduce**

1. Open Attached Save File [Neptune2.wgf.zip](https://github.com/widelands/widelands/files/7832746/Neptune2.wgf.zip)
2. Try to select Minerva 
3. -> Fail

**Expected behavior**

* I can select the Ships expedition Window without workarounds.
* The Workaroud should be explained in the Ship /Ferry tutorial

**Screenshots**

<img width="883" alt="Mienerva" src="https://user-images.githubusercontent.com/16598373/148634436-1bd12420-1379-4547-ac31-4e6fcd7067d6.png"> 

**Version:**
 - OS: macos Monterey Versions 12.1
 - Widelands Version: [1.1~git25586[c4ff57d@master]

**Additional context**

May this was the nearby Leonardo cacthing the click event ?

**Comment by Noordfrees** [comment]
You can select *Minerva* by clicking on the spot left to it. Ships are clickable over multiple fields. That *Leonardo* catches the click on the centre is because multiple ships can be on the same spot (bug #1408) and the game just picks one arbitrary ship when you click there. 

I'm not sure if there's really something that can be done about that, though if the other bug is solved in a way that prevents two ships from *ever* being on the same field this bug will go away as well. (See also the last two comments in the other issue.)

**Comment by Noordfrees** [comment]
Fixed by #5938
