### ISSUE TITLE
Add-On manager logs a user in although the user has been logged out prior

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5242]
Every time i start the addons manager i get logged in automatically although in a previous session i logged out.

**To Reproduce**
1. Start Add-on manager
2. Log out (if you where logged in once) or log in and log out again
3. Quit the game (or just leave the add-on manager)
4. Start Add-on manager again

You are logged in.

**Expected behavior**
The Add-Ons manager should recognize the last state (logged in/out). Maybe better is to force a user to login every time to prevent using the Add-ons manager from not trusted persons.

**Version:**
 - OS: archlinux
 - Widelands Version: 1.1~git25633[b0d4511@master] (Debug)

**Comment by Noordfrees** [comment]
I'm not sure about this. When entering the lobby you are also logged in automatically if your config file contains cached credentials, and the server behaviour is consistent with that. 

I would not be opposed to skipping the automatic connect that is made the moment you open the manager and only initiate the connection when you first need it (e.g. when fetching remotes). This would also save time when you just want to manage your local configuration without any remote interaction.

It would be easy to additionally skip the auto-login and always make an anonymous connection by default; however I think of this as a feature, because – is there really a reason why you *don't* want to be logged in in the connection?

On the server's side, it is a fresh login every time you open a connection, so if a user's account was deactivated in the meantime, then the next time they open the add-ons manager the login attempt fails regardless of whether it is an automatic or manual login.

**Comment by frankystone** [comment]
In contrast to the lobby one is able to upload content. So this can't be compared imho.

> is there really a reason why you don't want to be logged in in the connection?

Yes, just because i logged out manually? For scrolling through addons, watching the rates and screenshots, installing an addon, an account is not needed.

An account is only needed for rating an addon or for submitting addons/screenshots. I think having an account is a security feature and automatically logging in is undermining this aspect of security.

Anyway i am fine if the manager respects my wish: Logging out should mean logging out. Currently the manager promises functionality which doesn't hold.
