### ISSUE TITLE
In basic control tutorial, first objective appears twice

### ISSUE THREAD

**Issue by andy5995** [widelands/widelands#5336]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
In the basic control tutorial, the first objective appears two times, which is a bit confusing. It's mentioned in #4365, but it's not exactly clutter: it's duplicated information. The desired behavior would be for the welcome message->click ok->first objective.

**Screenshots**
Note the first window, and the text at the bottom:
![image](https://user-images.githubusercontent.com/16764864/160538830-2fbf2add-64fd-4d89-a56a-0a1c78405319.png)

After clicking "ok", the second window:

![image](https://user-images.githubusercontent.com/16764864/160538978-c5ae22ad-55bf-4b70-91a5-c0111390a046.png)

**Version:**
 - Widelands Version: 1.1~git50/77be5a6@master/(Debug)

**Additional context**
I spent some time trying to figure out how to fix it, but I could not. This bug is also in v1.0

**Comment by frankystone** [comment]
FYI: Some time ago a new concept of so called [Training wheels](https://www.widelands.org/documentation/autogen_auxiliary_init/) get implemented, see. e.g. https://github.com/widelands/widelands/pull/4369 and [other merged Pull requests](https://github.com/widelands/widelands/pull/4369). Since no one worked on this further, this concept got partially disabled…

To remove the objective text in the first window you have to exchange the function-call to  [campaign_message_with_objective()](https://www.widelands.org/documentation/autogen_auxiliary_messages/#campaign_message_with_objective) with a normal message_box:
https://github.com/widelands/widelands/blob/77be5a6ae332d72c91a6182eb744a548a6b49d7d/data/campaigns/tutorial01_basic_control.wmf/scripting/mission_thread.lua#L44-L45

The objective has to be added afterwards manually by using [add_campaign_objective()](https://www.widelands.org/documentation/autogen_auxiliary_messages/#add_campaign_objective)

If something is unclear, please ask again :-)

**Comment by andy5995** [comment]
> If something is unclear, please ask again :-)

Thanks @frankystone I think I can figure out from what you told me. I'll see what I can do...

**Comment by andy5995** [comment]
The behavior I mentioned above is not really a bug I think, just confusing. The objective is appearing the second time because the mission thread is clicking on the objectives button and opening the objectives window (as @hessenfarmer pointed out to me in #5338)
