### ISSUE TITLE
Last entry in debian/changelog is from 2018

### ISSUE THREAD

**Issue by andy5995** [widelands/widelands#5395]
Does debian/changelog need updating? The most recent entry appears to be from 2018...

https://github.com/widelands/widelands/blob/0ce5fb604e9bf884b0c4956500b61282cf6ae869/debian/changelog#L39

**Comment by tothxa** [comment]
Actually the whole `debian` directory is way outdated. I'm not sure whether anyone actually uses it, but in the current state it is probably more like a disservice to our users.

Unfortunately pulling the changes from salsa.debian.org wouldn't be of much use either, because they're stuck at Build-21. The packaging team is unresponsive too: there was no response to the Debian bug reports requesting update to v1.0, nor to my inquiry on debian-devel-games@lists.debian.org nearly 2 months ago.

(BTW they had their own patch for system wide minizip for the Build-21 package... looks somewhat similar to yours at first glance, but I didn't try to properly compare them)

**Comment by Noordfrees** [comment]
Our `debian` directory is used exclusively for our two PPAs (daily and stable). So it is updated whenever the daily builds fail on a new platform (every couple of Ubuntu release cycles or so; hasn't happened in a while). The changelog is not maintained though. 

Release packaging for the official repos is done independently from the main project.

**Comment by hessenfarmer** [comment]
@Noordfrees will there anything be done on this one. Does anything need to be done? (perhaps remove the changelog?)
Otherwise can we close this one?

**Comment by Noordfrees** [comment]
Removing it not possible, a changelog file is mandatory for debian packaging. The package also gets its version from the changelog. But let's close this as there is no need to properly maintain this just for the PPA. The "real" debian changelog can be found here: https://salsa.debian.org/games-team/widelands/-/blob/master/debian/changelog
