### ISSUE TITLE
Replace `directory` with `animation_directory` in animations

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#5411]
> > Im just saw you used "directory = " in the spritesheets definitions. However our documentation says this is deprecated. https://www.widelands.org/documentation/animations/ So better to use the animation_directory = again.
> 
> I'm sorry, wasn't aware of that. I corrected them for this PR. (but Frisian unit definitions still use `directory =` a lot)
> 
> _Originally posted by @tothxa in https://github.com/widelands/widelands/issues/5376#issuecomment-1122467012_

---

All unit definitions that still use `directory` should be converted to use `animation_directory`.

Support for the old syntax should be kept around for add-ons compatibility, and in order to ensure that it keeps working both syntaxes should be covered in the testsuite.

**Comment by Veracion** [comment]
Got a couple of questions regarding this:
- Should this only be corrected for the Frisians for now, or all in one fell swoop? I've seen there are about ~140 other files besides them still using the old way. More specifically, only immovables except two files.
- The Frisian soldiers use `directory` in order to store the images of the different soldier types in their own subfolders. Should it be changed regardless, i.e. putting all these sprites (~130) in one folder?
- There are these old comments in the code, see below. Should they be replaced or removed, as the old syntax will still be kept around?
`// TODO(GunChleoc): When all animations have been converted, require that animation_directory is not empty.`
- `basename` is deprecated as well and is also still being used lots. Maybe a follow-up issue should be created for this?

**Comment by Noordfrees** [comment]
It should be converted in all places where reasonably possible. For the frisian soldier I'd like to keep the directory structure as it's now and continue using the old syntax though, cluttering it all together would just be way too messy.

The deprecations and the TODO should be lifted IMHO since removing `basename` and requiring `animation_directory` would break add-ons. It is nonetheless a good idea to convert as many animation definitions to the new format as possible. 

For each supported syntax we should continue to have at least one official unit that uses it, to guard against regressions. Those units should be annotated accordingly so nobody cleans them up by accident later.
