### ISSUE TITLE
Question to the game_structure

### ISSUE THREAD

**Issue by Ahmad-fadl** [widelands/widelands#5460]
Hi,
This is rather a question than a Bug.
I'm Trying to extract a kind of wares' hierarchy out of the game for example (i assume ) to produce a helmet we need iron or some other wares. I need to extract this kind of relationships between the wares. 
I looked in the lua's data and did't find any buildcost for the wares (i only found buildcost for buildings or workers and so on).
In the Class ware_desc there is also no buildcost attribute.
does such a hierarchy exists for wares ? and if so where to find it?

**Comment by frankystone** [comment]
The buildcosts for wares are stored in the programs table (and sub tables) of a production site. E.g. for an Empire Helmet it is:
https://github.com/widelands/widelands/blob/b312d544d96a031f47fbda1af827629411557aeb/data/tribes/buildings/productionsites/empire/armorsmithy/init.lua#L68-L91

The `produce_armor_helmet`-table starting at line 80 the keyword `consumes` shows how many wares of each kind is needed to produce the ware. In this example one coal and 1 iron. See also [productionsite-Programs](https://www.widelands.org/documentation/autogen_tribes_productionsite_programs/)

There is also the [websites encyclopedia](https://www.widelands.org/encyclopedia/) but it shows only where which ware is produced. But it might be useful because each icon is clickable, e.g. in the graph for an [Empire Helmet](https://www.widelands.org/encyclopedia/empire/wares/armor_helmet/) you can click on the armorsmithy to see which wares needs the armorsmithy. But unfortunately not all shown wares might be needed to produce a helmet.

**Comment by Ahmad-fadl** [comment]
This was helpful thanks for clarification.
