### ISSUE TITLE
update.sh script no longer working

### ISSUE THREAD

**Issue by spth** [widelands/widelands#5463]
Since a few months, the update script hasn't been working for me any more.
Historically, by invoking ./update.sh I could update the game binary (it used to fetch the current version from git, and then recompiled anything that had changed).

Now I see something like.:

~~~~
philipp@notebook6:~/Spiele/widelands$ ./update.sh
…
 po/widelands/zh_TW.po                              |  20 +-
 169 files changed, 10241 insertions(+), 9997 deletions(-)
Call -j/--cores with a number, e.g. '-j 16'
~~~~

I've seen this bug on multiple systems (all of them Debian GNU/Linux on amd64).

Though I wonder if the bug is really in update.sh vs. compile.sh. The line that calls compile.sh from my update.sh is:

~~~~
./compile.sh --cores 15 --default-compiler --with-cross-opt --with-website --with-translations --do-tests --release --no-asan --no-tsan --with-xdg
~~~~

This is the update.sh I got after getting current git a few days ago, and then invoking ./compile-sh -r once.

**Comment by frankystone** [comment]
> ```
> ./compile.sh --cores 15 --default-compiler --with-cross-opt --with-website --with-translations --do-tests --release --no-asan --no-tsan --with-xdg
> ```

Does this line works when copying it into the terminal?

**Comment by spth** [comment]
No, it gives me the same error: `Call -j/--cores with a number, e.g. '-j 16`'.

**Comment by frankystone** [comment]
Since it works for me, the only thing i can think of is that the regular expression in line 203

https://github.com/widelands/widelands/blob/791a1b934e7fe3c5501ae94dab82fd5ef480820c/compile.sh#L202-L205

is maybe interpreted differently on your system? What is the output of `echo $SHELL`?

Just guessing...

**Comment by spth** [comment]
$SHELL is bash, but compile.sh has #!/bin/sh, and /bin/sh is dash.

**Comment by tothxa** [comment]
I have `dash` for `/bin/sh` too, and `--cores 15` is recognised as a number. (I get the message of more than max cores, so it should work if I had more than 10 cores)

**Comment by tothxa** [comment]
I think I've found the reason. `[^…]` in globs is actually a GNU extension, POSIX only allows `[!…]`. (why on Earth did they make it differ from regexs???) Looking at the changelog since buster/oldstable (which I have) they have something about disabling glob(3) from glibc, though for different bugs. This may explain why it works (erroneously) for me.
