### ISSUE TITLE
Shipwright is not building ferrys

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5521]
Sometimes a Shipwright of a ferry yard does not build a ferry. He leaves the building going to a place to build the ferry, the animation is working, but in result no ferry is made.
Sometimes the place where the shipwright goes not on the shore, so not close to water.

**To Reproduce**
1. load attached save game
2. start the ferry yard
3. see the shipwright leaves the building and watch him
4. sometimes no ferry is made, the wares are lost

Starting in verbose mode the console shows some
~~~~
[02:37:05.797 game] DEBUG: MO(4706,empire_ferry): [unemployed]: we are on shore
~~~~

but i am not sure if this is related to this issue.

**Expected behavior**
The shipwright should build a ferry. If this does not work (for whatever reason), the wares should not be lost.

**Version:**
 - OS: archlinux
 - Widelands Version: 1.1~git25849 (beedd78@master) Debug  
 
[No ferrys build.zip](https://github.com/widelands/widelands/files/9387402/No.ferrys.build.zip)

**Comment by Noordfrees** [comment]
Looks like the ferry is built on a node adjacent to 1 water and 5 land triangles. The ferry can only row along edges where both triangles are water though. So it cannot exist on this node.
Since `findspace=size:swim` causes this bug and `findspace=size:swim space` would cause valid nodes to be unusable, solution is to introduce another findspace size argument similar to `swim` which accepts a node if and only if it is reachable by a `CheckStepFerry`, and use the new argument for the shipwrights' ferry building programs.
