### ISSUE TITLE
Alternative map generators/editors accessible within the Widelands user interface, including available to install as an add-on

### ISSUE THREAD

**Issue by jasonkhanlar** [widelands/widelands#5529]
**Is your feature request related to a problem? Please describe.**
The problem:

In Single Player... -> New Random Game dialog I was experimenting with different values to generate maps and repeatedly seeing "Map Generation Error" message alert dialog stating "The random map generator was unable to generate a suitable map. This happens occasionally because the generator is still in beta stage. Please try again with slightly different settings."

This appears to be an already well known concern, given the message described within the game user interface. I'm sure there are many dozens of related issues regarding related things, however searching to see if any issues mention or discuss about additional or multiple map generators, instead of only a singular one generator, I did not find anything relevant or related. Therefore, I create this feature request to suggest the idea.

A while back I had discovered a game called Minetest, which I consider as a wonderful example to illustrate an approach of having multiple editors available, including as installable 3rd party addons. For example, see:

- https://minetest.net/#features
- https://wiki.minetest.net/Map_generator

Capabilities like this might be something worth considering, especially, depending on how buggy the existing editor is, that trying to fix the buggy editor to be not buggy, it might as well be easier to preserve the buggy editor to remain buggy (or fix it, I don't know how difficult it is or isn't, lol), and instead have the ability to create additional editors. And I think it's relatively common to see such developments begin as addons/plugins at first before being potentially integrated within official releases of games. Therefore, I think this approach to having alternative editors for Widelands seems worthy to consider, or at least mention/suggest. Heck, historically, whether playing Doom, Quake, Starcraft, or other games which had separate software editors to make level/map designs, there were always multiple different editors/tools, not just 1. Why should Widelands be any different to limit to only a single monopolistic* editor that everyone is forced to somehow make the best perfect editor (I'm not saying this is not possible, but otherwise given that the existing editor is buggy, without knowing any of the details to explain or know any of the history, this seems ridiculous)

Also: https://github.com/widelands/widelands/issues/5522#issuecomment-1222628189

> "In general the random map generator is a bit neglected… and probably buggy."

**Describe the solution you'd like**
Ability for multiple editors to exist to edit and save maps compatible with Widelands, accessible internally within the Widelands user interface.

**Additional context**
See https://github.com/widelands/widelands/issues/5522

\* Instead of "monopolistic" maybe monolithic comes to mind, instead of modular. e.g. https://medium.com/@berto168/monolithic-vs-modular-9b6d69684a2c "a monolithic framework typically provides a tightly coupled codebase that makes a lot of assumptions about how the code interacts with each other. ... a modular framework is more minimal and only provides the barebones functionality and structure for your application."

**Comment by hessenfarmer** [comment]
Well.     
first of all we need to distinguish between the map editor and the map generator.  
Imho the editor is quite usable and stable, although there are some open feature requests. The amount of maps uploaded on the homepage proves this from my perspective.    
The map generator however has some shortfalls. I used it succesfully a couple of times to create a quick draft of a map, Which I then edited to fit my likings with the editor. (Scenarios empire 3 and 4 were made this way).
But as said it is not always guaranteed to get playable maps right away. Therefore the random game feature is a bit impaired, which is reflected in the Ui note.     
I believe this is to some extent due to our biggest general problem which is lack of developers. So I am not very confident that somebody will come up with a better map generator while the existing generator proved to be hard to finalize.      
However our map file structure is open source so everyone is invited to contribute on this, although I would prefer improving the existing generator rather then starting a new one leaving us with 2 unfinished ones.       

Finally there is another way of creating maps, as we are able to load any settlers2 map you might use a s2 map generator as well.

**Comment by Noordfrees** [comment]
From a purely technical point of view, this should be easy to implement. A new add-on type that acts as a wrapper around a Lua script, a dropdown to select the generator, and a couple of new Lua functions to add the very few map-editing-related things that IIRC are not possible to do with Lua yet (starting positions, fine-grained resource control, bobs, waterway length).

I very much doubt that anyone will actually *make* a non-trivial generator though. If it was easy to write a good one, our built-in one would be much better ;) Also Lua has much slower performance which is why the C++ map generator will always be better in terms of speed than any add-on. 

However, it's easy to implement, and the possibility to script a generator more easily in Lua might attract people to try it who were previously put off by the pretty inaccessible C++ interface for map generation. So IMHO, why not.

Note that such a generator could also be used to generate maps that are not fully random but follow some more or less simple pattern instead. Auto-generation of maps with a mathematical pattern. Maybe if we drop the notion that this is intended only for truly-random maps the concept would turn out surprisingly popular.
