### ISSUE TITLE
All tribes should have recruits to make comparable worker statistics

### ISSUE THREAD

**Issue by hessenfarmer** [widelands/widelands#5564]
in a network game the worker statistics seems to be nor reflecting the red players workers.
![grafik](https://user-images.githubusercontent.com/43039887/189501206-98ce160a-7d0e-4482-91dd-5fc165dcc0ff.png)

**Comment by Noordfrees** [comment]
replay needed

**Comment by Noordfrees** [comment]
I assume this is from the tournament game Mars/the-x which I just watched? The reason then is that barbarians have 100 carriers and 100 recruits in each warehouse while amazons just have the 100 carriers and no recruits. See #4030. Please confirm whether this is the case and close this issue.

**Comment by hessenfarmer** [comment]
yes. It is from this game.     
another aspect apart from #4030 I see is that the tribes are not consistent. for recruits, so I would vote for having them for all tribes.      
Furthermore as they are noncost it would be sufficient to just build 10 of them for all warehouses.

**Comment by Noordfrees** [comment]
-1 for recruits for all tribes, they just add extra graphics workload without any value.

-1 also for having only 10 free workers per type. When you build more than ten roads at a time you would have to wait for enough carriers to be spawned to populate them all (or worse: the extra carriers would be sent from a far-away warehouse), because free workers are **not** created on demand. 

Let's just remove carriers and recruits from the stats and leave everything else as it is.

**Comment by hessenfarmer** [comment]
well,     
we could use the same graphics for the recruits as for the carriers as an interim placeholder until someone might find it more suitable to create different graphics.      
otherwise we could remove the recruits from the other tribes as well as their only effect is eyecandy for a short period in time while wlaking to the barracks.       
my suggestion was only to reduce the number of recruits not the number of workers if this is possible.

**Comment by frankystone** [comment]
I never understood having recruits with different graphics. They are created on the fly like carriers, but already visually equipped with some armor(?) (where does this armor come from?) and get another armor and a weapon to get a soldier.

What about removing recruits and use normal carriers for them? From my point of view this would make more sense because a player don't have to think about where the initial armor of a recruit comes from. But the recruits look can may be kept and make the barracks program a two step program: 

1. Carrier get a helmet → the carrier becomes a recruit (with it's actual graphics)
2. recruit get a spear → it will become a soldier

Something like that… needs some other changes to the UI though

And then remove carriers from the stats.

Otherwise i agree with Nordfrees.

**Comment by hessenfarmer** [comment]
well, as they are just nearly invisible eye candy we could simply remove the recruits from all tribes then. Or we leave them as they are and just clean up the stats. 
so I close the issue for now
