### ISSUE TITLE
Forbid dismantling military buildings while they are under attack

### ISSUE THREAD

**Issue by maciejjaskowski** [widelands/widelands#5810]
Please fill out the relevant sections below and delete the rest.

**Is your feature request related to a problem? Please describe.**
It's frustrating when the enemy dismantles a military building while being under attack. This tactic is helpful for the defender when he has multiple military buildings close to each other. Dismantling a military building before it's taken over finishes the battle, delays the ultimate defeat and sometimes saves some of the soldiers from being killed.

This tactic is also extremely unrealistic... who would start dismantling a fortress during a siege? ;)

**Describe the solution you'd like**
Dismantling or destroying a military building should be forbidden when the military building is under attack.

**Describe alternatives you've considered**

**Additional context**

**Implementation steps**
Haven't considered yet. I wonder if there is a deeper reason why such tactic is allowed atm.

**Comment by tothxa** [comment]
Actually enhancing/dismantling/destroying military buildings that are about to lose a battle is so much part of Widelands tactics, that the opposite is often requested (but voted down), ie. to not allow conquering military buildings at all, only destroying them on victory. It also has a real world equivalent: the scorched earth tactic.

The reason is that the default behaviour in Widelands, ie. conquering military buildings, results in a positive feedback, because it speeds up further attacks by the winner.

**Comment by frankystone** [comment]
Every player has the possibility to dismantle an own attacked building, so this tactic is open to all players. Instead of dismantling there is also the possibility to start upgrading a military building which is under attack, which can be a game changer.
widelands has only small abilities for military tactics, e.g. there are no long reaching weapons. Dismantling or upgrading a military building increases the amount of tactics a bit. Without this possibility some of the tournament games in the past were not so thrilling.

But since this question comes up from time to time again and again (e.g. [here](https://www.widelands.org/forum/topic/1466/) and [here](https://www.widelands.org/forum/topic/4551/)), probably confusing players, it needs some explanation somewhere.

**Comment by hessenfarmer** [comment]
I agree to @frankystone that we should explain it somewhere. Do we have or shall we create a widelands game tactics section in the FAQ? 
However I will close this soon as won't fix

**Comment by frankystone** [comment]
Probably [Tipps and Tricks](https://www.widelands.org/wiki/Tips%20and%20Tricks/) is the right place.

**Comment by tothxa** [comment]
> Probably [Tipps and Tricks](https://www.widelands.org/wiki/Tips%20and%20Tricks/) is the right place.

Well, it's already there: https://www.widelands.org/wiki/Tips%20and%20Tricks/#preventing-losses :) but it doesn't explicitly say that this possibility is intended and unlikely to change.

**Comment by tothxa** [comment]
Maybe the main FAQ should have a section on frequently requested changes and whether they are not planned with reasons or if they're just waiting for developers (like high resolution issues).

**Comment by frankystone** [comment]
> > Probably [Tipps and Tricks](https://www.widelands.org/wiki/Tips%20and%20Tricks/) is the right place.
> 
> Well, it's already there: https://www.widelands.org/wiki/Tips%20and%20Tricks/#preventing-losses :) but it doesn't explicitly say that this possibility is intended and unlikely to change.

:smile: I have read all except this chapter

Closing as won't fix
