### ISSUE TITLE
Single watch window mode does not work

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5830]
**Describe the bug**
In single watch window mode the watch window only remembers the last map position.

**To reproduce**
1. Turn on "Use single watchwindow mode" in Options
2. Start a game
3. Start watching a map position
4. Start watching another map position
5. Change watch window back to view 1
6. See error

**Expected behavior**
The view should go back to the first position.

**Version:**
 - OS: antix/Debian buster + backports
 - Widelands Version: v1.1 as well as 1.2~git26082 (fa28389@master)

**Additional context**
If noone noticed before, then probably noone actually uses single watchwindow mode. Could we remove it completely instead of fixing it? That would also mean one less config option. :)

**Comment by frankystone** [comment]
Personally i tried using the single watch window mode several times in the past... although i like this feature it turns out that switching the views inside the watch window is too fast for me and it shows always the position i don't want to view _now_ so i have to wait until it switches to the place i want to see. In the end i disabled this feature. So from my point of view this can be removed.

But i would vote for making a poll on the website to get an impression if other players use the single watch window mode before removing it.

**Comment by tothxa** [comment]
Some more testing showed that only the first slot is affected by this bug. If I assign more, then the later ones will be remembered correctly. I'll fix it then.
