### ISSUE TITLE
yet another msvc dependency problem

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5836]
See https://github.com/widelands/widelands/actions/runs/4571037234/jobs/8073630308 Turns out, it's not some transient error, but the version referenced by the runners (msys2-runtime-3.2.0.8) is deleted from the msys mirrors as obsolete.

Looks like we'll have to wait for https://github.com/microsoft/vcpkg/pull/30546

Once it's merged, will this be also rolled out in steps like the libvorbis one, still causing random breaks for a while?

**Comment by tothxa** [comment]
@matthiakl Could we override the msys runtime version somehow in our workflow setup until it's fixed? It looks like the error actually happens in `install-dependencies.sh`, so I suppose it's pulled in by the mingw toolchain package? So I have no idea how we could do it cleanly…

P.S. I forgot in the approval, so belatedly thank you for investigating the previous one.

**Comment by matthiakl** [comment]
> Could we override the msys runtime version somehow in our workflow setup until it's fixed?

Difficult. This would require changing some code lines inside the vcpkg repo during workflow, which would be highly experimental. ~Instead I propose to revert the vcpkg to the last successful cache and reuse it, until a newer version can be built (see PR).~ Edit: does not work, because we do not have a cache on master for current dependencies.

> It looks like the error actually happens in install-dependencies.sh, so I suppose it's pulled in by the mingw toolchain package? 

Did you notice that  install-dependencies.sh is now also used for vcpkg dependencies? Somehow the libiconv package pulls in mingw and msys2 as dependency... Don't ask me why.

**Comment by tothxa** [comment]
> > It looks like the error actually happens in install-dependencies.sh, so I suppose it's pulled in by the mingw toolchain package?
> 
> Did you notice that install-dependencies.sh is now also used for vcpkg dependencies? Somehow the libiconv package pulls in mingw and msys2 as dependency... Don't ask me why.

Yes, I knew that. But it turns out I hadn't looked closely enough to notice that `install_msys_pkgs()` has nothing to do with msvc/vcpkg. Sorry.
