### ISSUE TITLE
Re-enable filtering of pot generation times?

### ISSUE THREAD

**Issue by tothxa** [widelands/widelands#5936]
Direct commit https://github.com/widelands/widelands/commit/16b8c5495fb31ab7314d13404db3654318f7036f by @Noordfrees disabled the filtering of single line changes in the translation update script. Now every run produces new files with only the pot generation time changing.

As the change hadn't been discussed in advance, I'd like to ask what problem it was meant to solve. As far as I can see, the current behaviour is only a major regression.

In general, I understand that the filtering was rather simplistic, because it assumed that all single line changes were pot generation time changes. So we could add another check to make sure it is so.

What I noticed as a problem with transifex po file dates is that the last translator/date line gets reverted to some old commit when off-line translations are pushed through the command line client. But I don't think this is solved by the above change.

**Comment by Noordfrees** [comment]
A few weeks ago I made a rephrasing change in a file that was already fully translated, and the change wasn't pulled into the game. I investigated and it turned out that the file's diff after `tx pull` was a one-liner with no timestamp change, so the update script kept reverting it. Specifically it was about this change: https://github.com/widelands/widelands/commits/master/po/texts/nds.po 1ecb9c4d9c2935c295658dd2c39a25b1ca7f8caf

```diff
$ git show 1ecb9c4d9c2935c295658dd2c39a25b1ca7f8caf | grep po/texts/nds.po --after-context=10
diff --git a/po/texts/nds.po b/po/texts/nds.po
index 45f4e6c95c..83455b29db 100644
--- a/po/texts/nds.po
+++ b/po/texts/nds.po
@@ -834,7 +834,7 @@ msgid ""
 "touchpad scrolling in the ‘Options’ → ‘Edit keyboard and mouse actions’ "
 "menu. For example, moving the map view can be much more comfortable by "
 "scrolling instead of dragging with the right mouse button."
-msgstr "Wenn du up eenem Klappreekner mit Röögfeld büst, kannst du unner »Instellens« → »Knöppboord- un Muus-Befehlen bewarken« instellen, wat bi de Röögfeld-Verschuven passeren sall. To ’n Bispööl is dat vööl lichter, de Kaart-Sicht mit Rollen to verschuven as mit de rechten Muustast to trecken."
+msgstr "Wenn du up eenem Klappreekner mit Tastfeld büst, kannst du unner »Instellens« → »Knöppboord- un Muus-Befehlen bewarken« instellen, wat bi de Tastfeld-Verschuven passeren sall. To ’n Bispööl is dat vööl lichter, de Kaart-Sicht mit Rollen to verschuven as mit de rechten Muustast to trecken."
 
 #: ../../data/txts/tips/general_game.lua:106
 msgid ""
```

I guess a better solution would be to scan the file's diff whether anything that is neither a comment nor a blank line is being changed, instead of looking just at the number of lines affected.
