### ISSUE TITLE
Object pine_summer_old was not registered

### ISSUE THREAD

**Issue by MXB2001** [widelands/widelands#5939]
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
Loading a saved game from 1.0 in 1.1 of the Frisian Campaign where you land and make a port and have to appease the empire, etc. gives this message:
map objects: immoveable.cc:723 Object pine_summer_old was not registered
(see screenshot for exact wording)

**Expected behavior**
I was told 1.0 saves would work in 1.1

**Screenshots**
![Screenshot_20230608_200812](https://github.com/widelands/widelands/assets/65250870/cb54a0e9-e595-4655-92fd-0e28395318ca)

**Version:**
 - OS: Debian 10 (buster last point release)
 - Widelands Version: v1.1 release

**Comment by Noordfrees** [comment]
That is actually a [bug](https://github.com/widelands/widelands/issues/4907) in v1.0 that was fixed in v1.1. pine_summer_old is an add-on unit from the White Summer add-on which should not even be enabled in a scenario – in 1.0 it could still be enabled anyway, resulting in a corrupt savegame. 

Edit: could you please upload the savegame?

**Comment by MXB2001** [comment]
I have that add on installed. Would uninstalling it help or is it too late now? I found a second save that has a similar bug but with maple instead of pine. I suspect these saves were b21 saves continued in 1.0 as they are long games (almost 20 hrs). Hopefully there is a way to hack the savefile to save them since I've spent a lot of time on these two.

I'll upload both saves.

Frisian camp:
[FRISCAMP.zip](https://github.com/widelands/widelands/files/11709195/FRISCAMP.zip)

Europe Straits Bosporus:
[EUROPA.zip](https://github.com/widelands/widelands/files/11709197/EUROPA.zip)

PS. Interesting , had to zip them so that Git would accept them.

**Comment by Noordfrees** [comment]
Fixing the Europa savegame is as easy as adding White Summer to the list of required add-ons, so that add-on is now truly enabled:
[EUROPA.wgf.zip](https://github.com/widelands/widelands/files/11709892/EUROPA.wgf.zip)

For the campaign savegame, this does not fix the save since the combination of the v1.0 add-on bug and custom scenario units has broken the savegame.

**Comment by MXB2001** [comment]
Thanks very much for the fixed Europa, it works and I now have pretty red trees!

Pity about the campaign but I've edited the campaign conf to let me pass that scenario since I was at the stage of mopping up. The only thing I might need is a fri02.wcd for which I've asked for contributions of on the WL forum.
