### ISSUE TITLE
Crash in cookie priority queue

### ISSUE THREAD

**Issue by carli2** [widelands/widelands#6102]
```
widelands: /home/carli/projekte/widelands/src/logic/cookie_priority_queue.h:183: void CookiePriorityQueue<CPQType, Cmp, Cas>::push(CookiePriorityQueue<CPQType, Cmp, Cas>::CookieType*) [with CPQType = Widelands::Pathfield; Cmp = Widelands::Pathfield::LessCost; Cas = DefaultCookieAccessor<Widelands::Pathfield>; CookiePriorityQueue<CPQType, Cmp, Cas>::CookieType = Widelands::Pathfield]: Zusicherung »cookie_pos(elt_cookie) == BaseType::bad_pos()« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by Noordfrees** [comment]
Ouch. This is code that's basically never touched because it "just works".
Is this reproducible from the replay? If so could you upload the file please?

**Comment by carli2** [comment]
I hope, this is the right one. But it shouldn't since the last-modified date is 2:14hrs off the crash. Is every game recorded or do I have to use a certain option to get all games recorded?

[2023-08-18T16.56.15_single_player.zip](https://github.com/widelands/widelands/files/12383437/2023-08-18T16.56.15_single_player.zip)

**Comment by Noordfrees** [comment]
This bug is not reproducible from replay, however I think this is the same issue as a very weird and also non-reproducible hangup I get very occasionally in release builds. I think it's a race condition where a pathfinding call from UI code (e.g. roadbuilding) coincides with a pathfinding call from game logic code. And this messes up reentrant path finding stacking, resulting in an assert in debug builds and undefined behaviour (usually an infinite loop, but potentially even a desync) in release builds. Will add some mutex locks and hope this fixes it.

> Is every game recorded or do I have to use a certain option to get all games recorded?

By default, all games are recorded, unless you explicitly untick the "Write Replay" checkbox in the launch game setup (it's hidden under "Show More Options"). The exception to this is if you have an add-on enabled that's known to cause desyncs, in which case a prominent warning message is displayed and Widelands doesn't allow a replay to be created.
