### ISSUE TITLE
Build for Apple Silicon

### ISSUE THREAD

**Issue by klaus-halfmann** [widelands/widelands#6174]
As of https://github.com/actions/runner-images/issues/8439
M1 Macs are available for builds in gitlab now (have been waiting for this for ~2 years now?)

As of now we build for x86 Macs only but now we should try Apple Silicon as well.
Maybe we need testcases for only one of the builds.

As of the linked issue switching the runs-on: part should do the trick.

As of Now I found no differences in Intel Builds compared to ARM builds.
I expect the Issues with that "tainted" Flag like in my Manual builds,

**Additional context**
* I can compare the automated builds with my local ones in case we run into issues.

**Comment by matthiakl** [comment]
Currently the M1 runner are only in beta and available on the billed larger runners. So we need to wait until they are available for free public repos.

**Comment by radeva** [comment]
@klaus-halfmann @matthiakl You can try [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. They are on average 2x faster and 2x cheaper than GitHub's **AND** we have a **free tier for OSS projects** (see below).

# Install Instructions

1. Install [FlyCI app](https://github.com/apps/flyci-prod) and 
2. Easily replace one line of code and start using FlyCI runners:

```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```
# 500 mins/month Free for Public Repos

Since your repo is public, FlyCI offers **500 mins/month of free M1 runner usage** with the `flyci-macos-large-latest-m1` runner for public projects. 

Don't hesitate to contact us in case the free tier doesn't suit your needs or you experience any issues with the runners. Our team is here to support you!

Best Regards,
Veselina Radeva
Product Manager at [FlyCI](https://flyci.net/)
